/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckinIndexRouteImport } from './routes/checkin.index'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations/accept'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as AuthenticatedRegistrationsRouteImport } from './routes/_authenticated/registrations'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authTermsOfServiceRouteImport } from './routes/(auth)/terms-of-service'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authPrivacyPolicyRouteImport } from './routes/(auth)/privacy-policy'
import { Route as authPasswordResetConfirmRouteImport } from './routes/(auth)/password-reset-confirm'
import { Route as authPasswordResetRouteImport } from './routes/(auth)/password-reset'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as EventsSlugIndexRouteImport } from './routes/events.$slug.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedNposIndexRouteImport } from './routes/_authenticated/npos/index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as EventsSlugRegisterRouteImport } from './routes/events.$slug.register'
import { Route as AuthenticatedSettingsPasswordRouteImport } from './routes/_authenticated/settings/password'
import { Route as AuthenticatedSettingsConsentRouteImport } from './routes/_authenticated/settings/consent'
import { Route as AuthenticatedNposCreateRouteImport } from './routes/_authenticated/npos/create'
import { Route as AuthenticatedEventsCreateRouteImport } from './routes/_authenticated/events/create'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedEventsEventSlugRouteRouteImport } from './routes/_authenticated/events/$eventSlug/route'
import { Route as AuthenticatedNposNpoIdIndexRouteImport } from './routes/_authenticated/npos/$npoId.index'
import { Route as AuthenticatedEventsEventSlugIndexRouteImport } from './routes/_authenticated/events/$eventSlug/index'
import { Route as AuthenticatedNposNpoIdEditRouteImport } from './routes/_authenticated/npos/$npoId/edit'
import { Route as AuthenticatedEventsEventSlugEditRouteImport } from './routes/_authenticated/events/$eventSlug/edit'
import { Route as AuthenticatedEventsEventSlugAuctionItemsIndexRouteImport } from './routes/_authenticated/events/$eventSlug/auction-items/index'
import { Route as AuthenticatedEventsEventSlugAuctionItemsCreateRouteImport } from './routes/_authenticated/events/$eventSlug/auction-items/create'
import { Route as AuthenticatedEventsEventSlugAuctionItemsItemIdIndexRouteImport } from './routes/_authenticated/events/$eventSlug/auction-items/$itemId/index'
import { Route as AuthenticatedEventsEventSlugAuctionItemsItemIdEditRouteImport } from './routes/_authenticated/events/$eventSlug/auction-items/$itemId/edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinIndexRoute = CheckinIndexRouteImport.update({
  id: '/checkin/',
  path: '/checkin/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRegistrationsRoute =
  AuthenticatedRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authTermsOfServiceRoute = authTermsOfServiceRouteImport.update({
  id: '/(auth)/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authPrivacyPolicyRoute = authPrivacyPolicyRouteImport.update({
  id: '/(auth)/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const authPasswordResetConfirmRoute =
  authPasswordResetConfirmRouteImport.update({
    id: '/(auth)/password-reset-confirm',
    path: '/password-reset-confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const authPasswordResetRoute = authPasswordResetRouteImport.update({
  id: '/(auth)/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const EventsSlugIndexRoute = EventsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsSlugRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedNposIndexRoute = AuthenticatedNposIndexRouteImport.update({
  id: '/npos/',
  path: '/npos/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const EventsSlugRegisterRoute = EventsSlugRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => EventsSlugRoute,
} as any)
const AuthenticatedSettingsPasswordRoute =
  AuthenticatedSettingsPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsConsentRoute =
  AuthenticatedSettingsConsentRouteImport.update({
    id: '/consent',
    path: '/consent',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedNposCreateRoute = AuthenticatedNposCreateRouteImport.update({
  id: '/npos/create',
  path: '/npos/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsCreateRoute =
  AuthenticatedEventsCreateRouteImport.update({
    id: '/events/create',
    path: '/events/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventSlugRouteRoute =
  AuthenticatedEventsEventSlugRouteRouteImport.update({
    id: '/events/$eventSlug',
    path: '/events/$eventSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNposNpoIdIndexRoute =
  AuthenticatedNposNpoIdIndexRouteImport.update({
    id: '/npos/$npoId/',
    path: '/npos/$npoId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventSlugIndexRoute =
  AuthenticatedEventsEventSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEventsEventSlugRouteRoute,
  } as any)
const AuthenticatedNposNpoIdEditRoute =
  AuthenticatedNposNpoIdEditRouteImport.update({
    id: '/npos/$npoId/edit',
    path: '/npos/$npoId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventSlugEditRoute =
  AuthenticatedEventsEventSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedEventsEventSlugRouteRoute,
  } as any)
const AuthenticatedEventsEventSlugAuctionItemsIndexRoute =
  AuthenticatedEventsEventSlugAuctionItemsIndexRouteImport.update({
    id: '/auction-items/',
    path: '/auction-items/',
    getParentRoute: () => AuthenticatedEventsEventSlugRouteRoute,
  } as any)
const AuthenticatedEventsEventSlugAuctionItemsCreateRoute =
  AuthenticatedEventsEventSlugAuctionItemsCreateRouteImport.update({
    id: '/auction-items/create',
    path: '/auction-items/create',
    getParentRoute: () => AuthenticatedEventsEventSlugRouteRoute,
  } as any)
const AuthenticatedEventsEventSlugAuctionItemsItemIdIndexRoute =
  AuthenticatedEventsEventSlugAuctionItemsItemIdIndexRouteImport.update({
    id: '/auction-items/$itemId/',
    path: '/auction-items/$itemId/',
    getParentRoute: () => AuthenticatedEventsEventSlugRouteRoute,
  } as any)
const AuthenticatedEventsEventSlugAuctionItemsItemIdEditRoute =
  AuthenticatedEventsEventSlugAuctionItemsItemIdEditRouteImport.update({
    id: '/auction-items/$itemId/edit',
    path: '/auction-items/$itemId/edit',
    getParentRoute: () => AuthenticatedEventsEventSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/password-reset': typeof authPasswordResetRoute
  '/password-reset-confirm': typeof authPasswordResetConfirmRoute
  '/privacy-policy': typeof authPrivacyPolicyRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/terms-of-service': typeof authTermsOfServiceRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/home': typeof AuthenticatedHomeRoute
  '/registrations': typeof AuthenticatedRegistrationsRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/checkin/': typeof CheckinIndexRoute
  '/events/$eventSlug': typeof AuthenticatedEventsEventSlugRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/events/create': typeof AuthenticatedEventsCreateRoute
  '/npos/create': typeof AuthenticatedNposCreateRoute
  '/settings/consent': typeof AuthenticatedSettingsConsentRoute
  '/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/events/$slug/register': typeof EventsSlugRegisterRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/npos/': typeof AuthenticatedNposIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
  '/events/$eventSlug/edit': typeof AuthenticatedEventsEventSlugEditRoute
  '/npos/$npoId/edit': typeof AuthenticatedNposNpoIdEditRoute
  '/events/$eventSlug/': typeof AuthenticatedEventsEventSlugIndexRoute
  '/npos/$npoId/': typeof AuthenticatedNposNpoIdIndexRoute
  '/events/$eventSlug/auction-items/create': typeof AuthenticatedEventsEventSlugAuctionItemsCreateRoute
  '/events/$eventSlug/auction-items/': typeof AuthenticatedEventsEventSlugAuctionItemsIndexRoute
  '/events/$eventSlug/auction-items/$itemId/edit': typeof AuthenticatedEventsEventSlugAuctionItemsItemIdEditRoute
  '/events/$eventSlug/auction-items/$itemId/': typeof AuthenticatedEventsEventSlugAuctionItemsItemIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/password-reset': typeof authPasswordResetRoute
  '/password-reset-confirm': typeof authPasswordResetConfirmRoute
  '/privacy-policy': typeof authPrivacyPolicyRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/terms-of-service': typeof authTermsOfServiceRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/home': typeof AuthenticatedHomeRoute
  '/registrations': typeof AuthenticatedRegistrationsRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/checkin': typeof CheckinIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/events/create': typeof AuthenticatedEventsCreateRoute
  '/npos/create': typeof AuthenticatedNposCreateRoute
  '/settings/consent': typeof AuthenticatedSettingsConsentRoute
  '/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/events/$slug/register': typeof EventsSlugRegisterRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/npos': typeof AuthenticatedNposIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/events/$slug': typeof EventsSlugIndexRoute
  '/events/$eventSlug/edit': typeof AuthenticatedEventsEventSlugEditRoute
  '/npos/$npoId/edit': typeof AuthenticatedNposNpoIdEditRoute
  '/events/$eventSlug': typeof AuthenticatedEventsEventSlugIndexRoute
  '/npos/$npoId': typeof AuthenticatedNposNpoIdIndexRoute
  '/events/$eventSlug/auction-items/create': typeof AuthenticatedEventsEventSlugAuctionItemsCreateRoute
  '/events/$eventSlug/auction-items': typeof AuthenticatedEventsEventSlugAuctionItemsIndexRoute
  '/events/$eventSlug/auction-items/$itemId/edit': typeof AuthenticatedEventsEventSlugAuctionItemsItemIdEditRoute
  '/events/$eventSlug/auction-items/$itemId': typeof AuthenticatedEventsEventSlugAuctionItemsItemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/password-reset': typeof authPasswordResetRoute
  '/(auth)/password-reset-confirm': typeof authPasswordResetConfirmRoute
  '/(auth)/privacy-policy': typeof authPrivacyPolicyRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/terms-of-service': typeof authTermsOfServiceRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/registrations': typeof AuthenticatedRegistrationsRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/checkin/': typeof CheckinIndexRoute
  '/_authenticated/events/$eventSlug': typeof AuthenticatedEventsEventSlugRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/events/create': typeof AuthenticatedEventsCreateRoute
  '/_authenticated/npos/create': typeof AuthenticatedNposCreateRoute
  '/_authenticated/settings/consent': typeof AuthenticatedSettingsConsentRoute
  '/_authenticated/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/events/$slug/register': typeof EventsSlugRegisterRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/npos/': typeof AuthenticatedNposIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
  '/_authenticated/events/$eventSlug/edit': typeof AuthenticatedEventsEventSlugEditRoute
  '/_authenticated/npos/$npoId/edit': typeof AuthenticatedNposNpoIdEditRoute
  '/_authenticated/events/$eventSlug/': typeof AuthenticatedEventsEventSlugIndexRoute
  '/_authenticated/npos/$npoId/': typeof AuthenticatedNposNpoIdIndexRoute
  '/_authenticated/events/$eventSlug/auction-items/create': typeof AuthenticatedEventsEventSlugAuctionItemsCreateRoute
  '/_authenticated/events/$eventSlug/auction-items/': typeof AuthenticatedEventsEventSlugAuctionItemsIndexRoute
  '/_authenticated/events/$eventSlug/auction-items/$itemId/edit': typeof AuthenticatedEventsEventSlugAuctionItemsItemIdEditRoute
  '/_authenticated/events/$eventSlug/auction-items/$itemId/': typeof AuthenticatedEventsEventSlugAuctionItemsItemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/password-reset'
    | '/password-reset-confirm'
    | '/privacy-policy'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/terms-of-service'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/home'
    | '/registrations'
    | '/events/$slug'
    | '/invitations/accept'
    | '/checkin/'
    | '/events/$eventSlug'
    | '/errors/$error'
    | '/events/create'
    | '/npos/create'
    | '/settings/consent'
    | '/settings/password'
    | '/events/$slug/register'
    | '/events/'
    | '/npos/'
    | '/settings/'
    | '/events/$slug/'
    | '/events/$eventSlug/edit'
    | '/npos/$npoId/edit'
    | '/events/$eventSlug/'
    | '/npos/$npoId/'
    | '/events/$eventSlug/auction-items/create'
    | '/events/$eventSlug/auction-items/'
    | '/events/$eventSlug/auction-items/$itemId/edit'
    | '/events/$eventSlug/auction-items/$itemId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/password-reset'
    | '/password-reset-confirm'
    | '/privacy-policy'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/terms-of-service'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/home'
    | '/registrations'
    | '/invitations/accept'
    | '/checkin'
    | '/errors/$error'
    | '/events/create'
    | '/npos/create'
    | '/settings/consent'
    | '/settings/password'
    | '/events/$slug/register'
    | '/events'
    | '/npos'
    | '/settings'
    | '/events/$slug'
    | '/events/$eventSlug/edit'
    | '/npos/$npoId/edit'
    | '/events/$eventSlug'
    | '/npos/$npoId'
    | '/events/$eventSlug/auction-items/create'
    | '/events/$eventSlug/auction-items'
    | '/events/$eventSlug/auction-items/$itemId/edit'
    | '/events/$eventSlug/auction-items/$itemId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/password-reset'
    | '/(auth)/password-reset-confirm'
    | '/(auth)/privacy-policy'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(auth)/terms-of-service'
    | '/(auth)/verify-email'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/home'
    | '/_authenticated/registrations'
    | '/events/$slug'
    | '/invitations/accept'
    | '/checkin/'
    | '/_authenticated/events/$eventSlug'
    | '/_authenticated/errors/$error'
    | '/_authenticated/events/create'
    | '/_authenticated/npos/create'
    | '/_authenticated/settings/consent'
    | '/_authenticated/settings/password'
    | '/events/$slug/register'
    | '/_authenticated/events/'
    | '/_authenticated/npos/'
    | '/_authenticated/settings/'
    | '/events/$slug/'
    | '/_authenticated/events/$eventSlug/edit'
    | '/_authenticated/npos/$npoId/edit'
    | '/_authenticated/events/$eventSlug/'
    | '/_authenticated/npos/$npoId/'
    | '/_authenticated/events/$eventSlug/auction-items/create'
    | '/_authenticated/events/$eventSlug/auction-items/'
    | '/_authenticated/events/$eventSlug/auction-items/$itemId/edit'
    | '/_authenticated/events/$eventSlug/auction-items/$itemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authPasswordResetRoute: typeof authPasswordResetRoute
  authPasswordResetConfirmRoute: typeof authPasswordResetConfirmRoute
  authPrivacyPolicyRoute: typeof authPrivacyPolicyRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  authTermsOfServiceRoute: typeof authTermsOfServiceRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  EventsSlugRoute: typeof EventsSlugRouteWithChildren
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  CheckinIndexRoute: typeof CheckinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/': {
      id: '/checkin/'
      path: '/checkin'
      fullPath: '/checkin/'
      preLoaderRoute: typeof CheckinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/registrations': {
      id: '/_authenticated/registrations'
      path: '/registrations'
      fullPath: '/registrations'
      preLoaderRoute: typeof AuthenticatedRegistrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/terms-of-service': {
      id: '/(auth)/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof authTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/privacy-policy': {
      id: '/(auth)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof authPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/password-reset-confirm': {
      id: '/(auth)/password-reset-confirm'
      path: '/password-reset-confirm'
      fullPath: '/password-reset-confirm'
      preLoaderRoute: typeof authPasswordResetConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/password-reset': {
      id: '/(auth)/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof authPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/events/$slug/': {
      id: '/events/$slug/'
      path: '/'
      fullPath: '/events/$slug/'
      preLoaderRoute: typeof EventsSlugIndexRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/npos/': {
      id: '/_authenticated/npos/'
      path: '/npos'
      fullPath: '/npos/'
      preLoaderRoute: typeof AuthenticatedNposIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/events/$slug/register': {
      id: '/events/$slug/register'
      path: '/register'
      fullPath: '/events/$slug/register'
      preLoaderRoute: typeof EventsSlugRegisterRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/_authenticated/settings/password': {
      id: '/_authenticated/settings/password'
      path: '/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof AuthenticatedSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/consent': {
      id: '/_authenticated/settings/consent'
      path: '/consent'
      fullPath: '/settings/consent'
      preLoaderRoute: typeof AuthenticatedSettingsConsentRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/npos/create': {
      id: '/_authenticated/npos/create'
      path: '/npos/create'
      fullPath: '/npos/create'
      preLoaderRoute: typeof AuthenticatedNposCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/create': {
      id: '/_authenticated/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof AuthenticatedEventsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventSlug': {
      id: '/_authenticated/events/$eventSlug'
      path: '/events/$eventSlug'
      fullPath: '/events/$eventSlug'
      preLoaderRoute: typeof AuthenticatedEventsEventSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/npos/$npoId/': {
      id: '/_authenticated/npos/$npoId/'
      path: '/npos/$npoId'
      fullPath: '/npos/$npoId/'
      preLoaderRoute: typeof AuthenticatedNposNpoIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventSlug/': {
      id: '/_authenticated/events/$eventSlug/'
      path: '/'
      fullPath: '/events/$eventSlug/'
      preLoaderRoute: typeof AuthenticatedEventsEventSlugIndexRouteImport
      parentRoute: typeof AuthenticatedEventsEventSlugRouteRoute
    }
    '/_authenticated/npos/$npoId/edit': {
      id: '/_authenticated/npos/$npoId/edit'
      path: '/npos/$npoId/edit'
      fullPath: '/npos/$npoId/edit'
      preLoaderRoute: typeof AuthenticatedNposNpoIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventSlug/edit': {
      id: '/_authenticated/events/$eventSlug/edit'
      path: '/edit'
      fullPath: '/events/$eventSlug/edit'
      preLoaderRoute: typeof AuthenticatedEventsEventSlugEditRouteImport
      parentRoute: typeof AuthenticatedEventsEventSlugRouteRoute
    }
    '/_authenticated/events/$eventSlug/auction-items/': {
      id: '/_authenticated/events/$eventSlug/auction-items/'
      path: '/auction-items'
      fullPath: '/events/$eventSlug/auction-items/'
      preLoaderRoute: typeof AuthenticatedEventsEventSlugAuctionItemsIndexRouteImport
      parentRoute: typeof AuthenticatedEventsEventSlugRouteRoute
    }
    '/_authenticated/events/$eventSlug/auction-items/create': {
      id: '/_authenticated/events/$eventSlug/auction-items/create'
      path: '/auction-items/create'
      fullPath: '/events/$eventSlug/auction-items/create'
      preLoaderRoute: typeof AuthenticatedEventsEventSlugAuctionItemsCreateRouteImport
      parentRoute: typeof AuthenticatedEventsEventSlugRouteRoute
    }
    '/_authenticated/events/$eventSlug/auction-items/$itemId/': {
      id: '/_authenticated/events/$eventSlug/auction-items/$itemId/'
      path: '/auction-items/$itemId'
      fullPath: '/events/$eventSlug/auction-items/$itemId/'
      preLoaderRoute: typeof AuthenticatedEventsEventSlugAuctionItemsItemIdIndexRouteImport
      parentRoute: typeof AuthenticatedEventsEventSlugRouteRoute
    }
    '/_authenticated/events/$eventSlug/auction-items/$itemId/edit': {
      id: '/_authenticated/events/$eventSlug/auction-items/$itemId/edit'
      path: '/auction-items/$itemId/edit'
      fullPath: '/events/$eventSlug/auction-items/$itemId/edit'
      preLoaderRoute: typeof AuthenticatedEventsEventSlugAuctionItemsItemIdEditRouteImport
      parentRoute: typeof AuthenticatedEventsEventSlugRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsConsentRoute: typeof AuthenticatedSettingsConsentRoute
  AuthenticatedSettingsPasswordRoute: typeof AuthenticatedSettingsPasswordRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsConsentRoute: AuthenticatedSettingsConsentRoute,
    AuthenticatedSettingsPasswordRoute: AuthenticatedSettingsPasswordRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedEventsEventSlugRouteRouteChildren {
  AuthenticatedEventsEventSlugEditRoute: typeof AuthenticatedEventsEventSlugEditRoute
  AuthenticatedEventsEventSlugIndexRoute: typeof AuthenticatedEventsEventSlugIndexRoute
  AuthenticatedEventsEventSlugAuctionItemsCreateRoute: typeof AuthenticatedEventsEventSlugAuctionItemsCreateRoute
  AuthenticatedEventsEventSlugAuctionItemsIndexRoute: typeof AuthenticatedEventsEventSlugAuctionItemsIndexRoute
  AuthenticatedEventsEventSlugAuctionItemsItemIdEditRoute: typeof AuthenticatedEventsEventSlugAuctionItemsItemIdEditRoute
  AuthenticatedEventsEventSlugAuctionItemsItemIdIndexRoute: typeof AuthenticatedEventsEventSlugAuctionItemsItemIdIndexRoute
}

const AuthenticatedEventsEventSlugRouteRouteChildren: AuthenticatedEventsEventSlugRouteRouteChildren =
  {
    AuthenticatedEventsEventSlugEditRoute:
      AuthenticatedEventsEventSlugEditRoute,
    AuthenticatedEventsEventSlugIndexRoute:
      AuthenticatedEventsEventSlugIndexRoute,
    AuthenticatedEventsEventSlugAuctionItemsCreateRoute:
      AuthenticatedEventsEventSlugAuctionItemsCreateRoute,
    AuthenticatedEventsEventSlugAuctionItemsIndexRoute:
      AuthenticatedEventsEventSlugAuctionItemsIndexRoute,
    AuthenticatedEventsEventSlugAuctionItemsItemIdEditRoute:
      AuthenticatedEventsEventSlugAuctionItemsItemIdEditRoute,
    AuthenticatedEventsEventSlugAuctionItemsItemIdIndexRoute:
      AuthenticatedEventsEventSlugAuctionItemsItemIdIndexRoute,
  }

const AuthenticatedEventsEventSlugRouteRouteWithChildren =
  AuthenticatedEventsEventSlugRouteRoute._addFileChildren(
    AuthenticatedEventsEventSlugRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedRegistrationsRoute: typeof AuthenticatedRegistrationsRoute
  AuthenticatedEventsEventSlugRouteRoute: typeof AuthenticatedEventsEventSlugRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedEventsCreateRoute: typeof AuthenticatedEventsCreateRoute
  AuthenticatedNposCreateRoute: typeof AuthenticatedNposCreateRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedNposIndexRoute: typeof AuthenticatedNposIndexRoute
  AuthenticatedNposNpoIdEditRoute: typeof AuthenticatedNposNpoIdEditRoute
  AuthenticatedNposNpoIdIndexRoute: typeof AuthenticatedNposNpoIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedRegistrationsRoute: AuthenticatedRegistrationsRoute,
  AuthenticatedEventsEventSlugRouteRoute:
    AuthenticatedEventsEventSlugRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedEventsCreateRoute: AuthenticatedEventsCreateRoute,
  AuthenticatedNposCreateRoute: AuthenticatedNposCreateRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedNposIndexRoute: AuthenticatedNposIndexRoute,
  AuthenticatedNposNpoIdEditRoute: AuthenticatedNposNpoIdEditRoute,
  AuthenticatedNposNpoIdIndexRoute: AuthenticatedNposNpoIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EventsSlugRouteChildren {
  EventsSlugRegisterRoute: typeof EventsSlugRegisterRoute
  EventsSlugIndexRoute: typeof EventsSlugIndexRoute
}

const EventsSlugRouteChildren: EventsSlugRouteChildren = {
  EventsSlugRegisterRoute: EventsSlugRegisterRoute,
  EventsSlugIndexRoute: EventsSlugIndexRoute,
}

const EventsSlugRouteWithChildren = EventsSlugRoute._addFileChildren(
  EventsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authPasswordResetRoute: authPasswordResetRoute,
  authPasswordResetConfirmRoute: authPasswordResetConfirmRoute,
  authPrivacyPolicyRoute: authPrivacyPolicyRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  authTermsOfServiceRoute: authTermsOfServiceRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  EventsSlugRoute: EventsSlugRouteWithChildren,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  CheckinIndexRoute: CheckinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
