openapi: 3.1.0
info:
  title: NPO Context API
  description: API endpoints for retrieving role-based NPO lists
  version: 1.0.0

paths:
  /api/v1/npos:
    get:
      summary: List NPOs accessible to authenticated user
      description: |
        Returns NPOs based on user role:
        - SuperAdmin: All NPOs (no filtering)
        - NPO Admin: Assigned NPO(s) only
        - Event Coordinator: NPOs with registered events (read-only)
        - Staff: Assigned NPO only (read-only)
        - Donor: Empty list (no access)

        Used to populate the NPO context selector dropdown.
      operationId: listNpos
      tags:
        - NPOs
      security:
        - BearerAuth: []
      parameters:
        - name: status
          in: query
          required: false
          description: "Filter by NPO status (default: approved only)"
          schema:
            type: string
            enum:
              - draft
              - pending_approval
              - approved
              - suspended
              - rejected
              - all
            default: approved
        - name: page
          in: query
          required: false
          description: Page number for pagination (1-indexed)
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          required: false
          description: Items per page (max 100)
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
      responses:
        '200':
          description: List of accessible NPOs
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        name:
                          type: string
                          example: "Bay Area Food Bank"
                        email:
                          type: string
                          format: email
                        status:
                          type: string
                          enum: ["draft", "pending_approval", "approved", "suspended", "rejected"]
                        created_at:
                          type: string
                          format: date-time
                  total:
                    type: integer
                    example: 42
                  page:
                    type: integer
                    example: 1
                  limit:
                    type: integer
                    example: 50
                  has_more:
                    type: boolean
                    example: false
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Not authenticated"
        '403':
          description: Forbidden (Donor role attempting to list NPOs)
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "You do not have permission to list NPOs"

  /api/v1/events:
    get:
      summary: List events accessible to authenticated user
      description: |
        Returns events filtered by role and NPO context:
        - SuperAdmin: All events (filtered by npoId if provided)
        - NPO Admin: Events within assigned NPO(s)
        - Event Coordinator: Assigned events only
        - Staff: Events they're assigned to
        - Donor: Empty list (no access in admin PWA)
      operationId: listEvents
      tags:
        - Events
      security:
        - BearerAuth: []
      parameters:
        - name: npoId
          in: query
          required: false
          description: Filter by NPO context (from NPO selector state)
          schema:
            type: string
            format: uuid
            nullable: true
        - name: status
          in: query
          required: false
          description: Filter by event status
          schema:
            type: string
            enum:
              - "draft"
              - "active"
              - "closed"
              - "all"
            default: "all"
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
      responses:
        '200':
          description: List of accessible events
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        title:
                          type: string
                        npo_id:
                          type: string
                          format: uuid
                        npo_name:
                          type: string
                        status:
                          type: string
                        start_datetime:
                          type: string
                          format: date-time
                        end_datetime:
                          type: string
                          format: date-time
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
                  has_more:
                    type: boolean
        '401':
          description: Not authenticated
        '403':
          description: Forbidden

  /api/v1/users:
    get:
      summary: List users accessible to authenticated user
      description: |
        Returns users filtered by role:
        - SuperAdmin: All users (filtered by npoId if provided)
        - NPO Admin: Users within assigned NPO(s)
        - Event Coordinator: Users registered for assigned events (read-only)
        - Staff: Users registered for assigned events (read-only)
        - Donor: Empty list
      operationId: listUsers
      tags:
        - Users
      security:
        - BearerAuth: []
      parameters:
        - name: npoId
          in: query
          required: false
          schema:
            type: string
            format: uuid
            nullable: true
        - name: role
          in: query
          required: false
          description: Filter by user role
          schema:
            type: string
            enum:
              - "SuperAdmin"
              - "NPO Admin"
              - "Event Coordinator"
              - "Staff"
              - "Donor"
              - "all"
            default: "all"
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
      responses:
        '200':
          description: List of accessible users
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        first_name:
                          type: string
                        last_name:
                          type: string
                        email:
                          type: string
                          format: email
                        role:
                          type: object
                          properties:
                            name:
                              type: string
                        is_active:
                          type: boolean
                        email_verified:
                          type: boolean
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
                  has_more:
                    type: boolean
        '401':
          description: Not authenticated
        '403':
          description: Forbidden

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
