openapi: 3.1.0
info:
  title: Donor PWA Event Homepage API
  description: API endpoints for the donor PWA event homepage feature
  version: 1.0.0
  contact:
    name: Fundrbolt Platform
    email: dev@fundrbolt.app

servers:
  - url: /api/v1
    description: API v1

paths:
  /registrations/events-with-branding:
    get:
      summary: Get registered events with branding
      description: |
        Returns all events the authenticated user is registered for,
        with resolved branding (event colors → NPO colors → defaults).
        Events are sorted with upcoming events first (by date ASC),
        then past events (by date DESC).
      operationId: getRegisteredEventsWithBranding
      tags:
        - Registrations
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of registered events with branding
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisteredEventsResponse'
        '401':
          description: Unauthorized - authentication required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /events/{eventId}/auction-items:
    get:
      summary: List auction items for gallery
      description: |
        Returns paginated auction items for an event.
        Supports filtering by auction type and infinite scroll pagination.
        Items are sorted by creation date DESC, then by starting bid DESC.
      operationId: listAuctionItemsForGallery
      tags:
        - Auction Items
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Event UUID
        - name: auction_type
          in: query
          required: false
          schema:
            type: string
            enum: [silent, live, all]
            default: all
          description: Filter by auction type (all = no filter)
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number (1-indexed)
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 20
          description: Items per page
        - name: sort_by
          in: query
          required: false
          schema:
            type: string
            enum: [newest, highest_bid]
            default: highest_bid
          description: Sort order (highest_bid = highest current bid first, items without bids use starting_bid)
      responses:
        '200':
          description: Paginated list of auction items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionItemGalleryResponse'
        '404':
          description: Event not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisteredEventsResponse:
      type: object
      required:
        - events
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/RegisteredEventWithBranding'

    RegisteredEventWithBranding:
      type: object
      required:
        - id
        - name
        - slug
        - event_datetime
        - timezone
        - is_past
        - is_upcoming
        - primary_color
        - secondary_color
        - background_color
        - accent_color
        - npo_name
      properties:
        id:
          type: string
          format: uuid
          description: Event UUID
        name:
          type: string
          description: Event name
          example: "Annual Charity Gala 2025"
        slug:
          type: string
          description: URL-safe event identifier
          example: "annual-charity-gala-2025"
        event_datetime:
          type: string
          format: date-time
          description: Event start datetime (ISO 8601)
          example: "2025-12-20T18:00:00Z"
        timezone:
          type: string
          description: Event timezone
          example: "America/New_York"
        is_past:
          type: boolean
          description: True if event datetime has passed
        is_upcoming:
          type: boolean
          description: True if event is within 30 days
        thumbnail_url:
          type: string
          format: uri
          nullable: true
          description: Event image or NPO logo as fallback
        primary_color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
          description: Primary branding color (hex)
          example: "#FF5733"
        secondary_color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
          description: Secondary branding color (hex)
          example: "#33FF57"
        background_color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
          description: Background color (hex)
          example: "#FFFFFF"
        accent_color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
          description: Accent color (hex)
          example: "#3357FF"
        npo_name:
          type: string
          description: Organizing NPO name
          example: "Local Food Bank"
        npo_logo_url:
          type: string
          format: uri
          nullable: true
          description: NPO logo URL

    AuctionItemGalleryResponse:
      type: object
      required:
        - items
        - pagination
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/AuctionItemGalleryItem'
        pagination:
          $ref: '#/components/schemas/PaginationInfo'

    AuctionItemGalleryItem:
      type: object
      required:
        - id
        - title
        - auction_type
        - starting_bid
      properties:
        id:
          type: string
          format: uuid
          description: Auction item UUID
        title:
          type: string
          description: Item title
          example: "Weekend Getaway Package"
        description:
          type: string
          nullable: true
          description: Item description (truncated to ~100 chars)
          example: "Luxury hotel stay for two with spa..."
        auction_type:
          type: string
          enum: [silent, live]
          description: Auction type
        thumbnail_url:
          type: string
          format: uri
          nullable: true
          description: Item thumbnail image URL
        starting_bid:
          type: number
          format: decimal
          description: Starting bid amount
          example: 100.00
        current_bid:
          type: number
          format: decimal
          nullable: true
          description: Current highest bid (null if no bids)
          example: 150.00
        bid_count:
          type: integer
          minimum: 0
          default: 0
          description: Number of bids placed

    PaginationInfo:
      type: object
      required:
        - page
        - limit
        - total
        - total_pages
        - has_more
      properties:
        page:
          type: integer
          minimum: 1
          description: Current page number
        limit:
          type: integer
          minimum: 1
          description: Items per page
        total:
          type: integer
          minimum: 0
          description: Total number of items
        total_pages:
          type: integer
          minimum: 0
          description: Total number of pages
        has_more:
          type: boolean
          description: True if more pages exist

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Event not found"
