openapi: 3.0.3
info:
  title: Auction Item Bulk Import
  version: 1.0.0
paths:
  /api/v1/admin/events/{event_id}/auction-items/import/preflight:
    post:
      summary: Preflight validation for auction item import
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                zip_file:
                  type: string
                  format: binary
              required:
                - zip_file
      responses:
        "200":
          description: Preflight report
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImportReport"
        "400":
          description: Invalid package or validation errors
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "413":
          description: Payload too large
  /api/v1/admin/events/{event_id}/auction-items/import/commit:
    post:
      summary: Commit a validated auction item import
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                zip_file:
                  type: string
                  format: binary
              required:
                - zip_file
      responses:
        "200":
          description: Commit report
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImportReport"
        "400":
          description: Invalid package or commit errors
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "413":
          description: Payload too large
components:
  schemas:
    ImportReport:
      type: object
      properties:
        total_rows:
          type: integer
        created_count:
          type: integer
        updated_count:
          type: integer
        skipped_count:
          type: integer
        error_count:
          type: integer
        warnings_count:
          type: integer
        rows:
          type: array
          items:
            $ref: "#/components/schemas/ImportRowResult"
      required:
        - total_rows
        - created_count
        - updated_count
        - skipped_count
        - error_count
        - rows
    ImportRowResult:
      type: object
      properties:
        row_number:
          type: integer
        external_id:
          type: string
        status:
          type: string
          enum: [created, updated, skipped, error]
        message:
          type: string
        image_status:
          type: string
          enum: [ok, missing, invalid]
      required:
        - row_number
        - status
        - message
