"""add media_type mime_type blob_name to event_media

Revision ID: 5c1511bffa16
Revises: 9ee8000056a7
Create Date: 2025-11-10 22:02:39.187603

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "5c1511bffa16"
down_revision = "9ee8000056a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_contact_submissions_created_at"), table_name="contact_submissions")
    op.drop_index(op.f("idx_contact_submissions_ip_created"), table_name="contact_submissions")
    op.drop_index(op.f("idx_contact_submissions_status"), table_name="contact_submissions")
    op.drop_table("contact_submissions")
    op.drop_index(op.f("idx_testimonials_created_by"), table_name="testimonials")
    op.drop_index(
        op.f("idx_testimonials_published_order"),
        table_name="testimonials",
        postgresql_where="(deleted_at IS NULL)",
    )
    op.drop_index(
        op.f("idx_testimonials_role"),
        table_name="testimonials",
        postgresql_where="((deleted_at IS NULL) AND (is_published = true))",
    )
    op.drop_table("testimonials")
    op.drop_index(op.f("idx_audit_logs_action"), table_name="audit_logs")
    op.drop_index(op.f("idx_audit_logs_action_created"), table_name="audit_logs")
    op.drop_index(op.f("idx_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("idx_audit_logs_ip_address"), table_name="audit_logs")
    op.drop_index(
        op.f("idx_audit_logs_metadata_gin"), table_name="audit_logs", postgresql_using="gin"
    )
    op.drop_index(op.f("idx_audit_logs_user_created"), table_name="audit_logs")
    op.drop_index(op.f("idx_audit_logs_user_id"), table_name="audit_logs")
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_ip_address"), "audit_logs", ["ip_address"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.drop_index(op.f("idx_consent_audit_logs_action"), table_name="consent_audit_logs")
    op.drop_index(op.f("idx_consent_audit_logs_created_at"), table_name="consent_audit_logs")
    op.drop_index(
        op.f("idx_consent_audit_logs_details_gin"),
        table_name="consent_audit_logs",
        postgresql_using="gin",
    )
    op.drop_index(op.f("idx_consent_audit_logs_user_id"), table_name="consent_audit_logs")
    op.create_index(
        op.f("ix_consent_audit_logs_action"), "consent_audit_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_consent_audit_logs_created_at"), "consent_audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_consent_audit_logs_user_id"), "consent_audit_logs", ["user_id"], unique=False
    )
    op.drop_index(op.f("idx_cookie_consents_created_at"), table_name="cookie_consents")
    op.drop_index(op.f("idx_cookie_consents_session_id"), table_name="cookie_consents")
    op.drop_index(op.f("idx_cookie_consents_user_id"), table_name="cookie_consents")
    op.create_index(
        op.f("ix_cookie_consents_session_id"), "cookie_consents", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_cookie_consents_user_id"), "cookie_consents", ["user_id"], unique=False
    )
    op.alter_column(
        "event_links",
        "label",
        existing_type=sa.VARCHAR(length=255),
        comment="Display label (e.g., 'Event Promo Video')",
        existing_nullable=True,
    )
    op.alter_column(
        "event_links",
        "platform",
        existing_type=sa.VARCHAR(length=50),
        comment="Platform name (YouTube, Vimeo, Facebook, etc.)",
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_event_links_link_type"), table_name="event_links")
    # Create event_media_type enum
    op.execute("CREATE TYPE event_media_type AS ENUM ('image', 'video', 'flyer')")
    op.add_column(
        "event_media",
        sa.Column(
            "media_type",
            sa.Enum("image", "video", "flyer", name="event_media_type"),
            nullable=False,
            comment="Type of media: image, video, or flyer",
        ),
    )
    op.add_column(
        "event_media",
        sa.Column(
            "mime_type",
            sa.String(length=100),
            nullable=False,
            comment="MIME type for validation (e.g., image/jpeg)",
        ),
    )
    op.add_column(
        "event_media",
        sa.Column(
            "blob_name",
            sa.String(length=500),
            nullable=False,
            comment="Azure Blob Storage blob name/path",
        ),
    )
    op.alter_column(
        "event_media",
        "file_url",
        existing_type=sa.VARCHAR(length=500),
        comment="Azure Blob Storage URL",
        existing_nullable=False,
    )
    op.alter_column(
        "event_media",
        "file_name",
        existing_type=sa.VARCHAR(length=255),
        comment="Original filename",
        existing_nullable=False,
    )
    op.alter_column(
        "event_media",
        "file_type",
        existing_type=sa.VARCHAR(length=100),
        comment="MIME type (e.g., image/png)",
        existing_nullable=False,
    )
    op.alter_column(
        "event_media",
        "file_size",
        existing_type=sa.INTEGER(),
        comment="File size in bytes",
        existing_nullable=False,
    )
    op.alter_column(
        "event_media",
        "display_order",
        existing_type=sa.INTEGER(),
        comment="Order for gallery display",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_index(op.f("idx_event_media_display_order"), table_name="event_media")
    op.alter_column(
        "events",
        "timezone",
        existing_type=sa.VARCHAR(length=50),
        comment="IANA timezone name (e.g., America/Chicago)",
        existing_nullable=False,
    )
    op.alter_column(
        "events",
        "description",
        existing_type=sa.TEXT(),
        comment="Rich text description (Markdown format)",
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "logo_url",
        existing_type=sa.VARCHAR(length=500),
        comment="Event-specific logo (Azure Blob URL)",
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "primary_color",
        existing_type=sa.VARCHAR(length=7),
        comment="Hex color code (e.g., #FF5733)",
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "secondary_color",
        existing_type=sa.VARCHAR(length=7),
        comment="Hex color code (e.g., #33C4FF)",
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "version",
        existing_type=sa.INTEGER(),
        comment="Version counter for optimistic locking",
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "food_options",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment="Option name (e.g., 'Chicken', 'Vegetarian')",
        existing_nullable=False,
    )
    op.alter_column(
        "food_options",
        "description",
        existing_type=sa.TEXT(),
        comment="Optional detailed description",
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_food_options_display_order"), table_name="food_options")
    op.alter_column(
        "invitations",
        "invited_user_id",
        existing_type=sa.UUID(),
        comment="Set when existing user is invited",
        existing_nullable=True,
    )
    op.alter_column(
        "invitations",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment="Invitation target email address",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "first_name",
        existing_type=sa.VARCHAR(length=100),
        comment="Optional first name to pre-fill registration",
        existing_nullable=True,
    )
    op.alter_column(
        "invitations",
        "last_name",
        existing_type=sa.VARCHAR(length=100),
        comment="Optional last name to pre-fill registration",
        existing_nullable=True,
    )
    op.alter_column(
        "invitations",
        "role",
        existing_type=sa.VARCHAR(length=50),
        comment="Role to assign: admin, co_admin, or staff",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "status",
        existing_type=postgresql.ENUM(
            "pending", "accepted", "expired", "revoked", name="invitation_status"
        ),
        type_=sa.Enum(
            "pending", "accepted", "expired", "revoked", name="invitation_status", native_enum=False
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::invitation_status"),
    )
    op.alter_column(
        "invitations",
        "token_hash",
        existing_type=sa.VARCHAR(length=255),
        comment="Hashed JWT invitation token",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Invitation expiry (7 days from creation)",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "accepted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When invitation was accepted",
        existing_nullable=True,
    )
    op.drop_constraint(op.f("invitations_token_hash_key"), "invitations", type_="unique")
    op.drop_index(op.f("ix_invitations_email_status"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_npo_status"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_token_hash"), table_name="invitations")
    op.create_index(op.f("ix_invitations_token_hash"), "invitations", ["token_hash"], unique=True)
    op.drop_index(op.f("idx_legal_documents_published_at"), table_name="legal_documents")
    op.drop_index(op.f("idx_legal_documents_status"), table_name="legal_documents")
    op.drop_index(op.f("idx_legal_documents_type_version"), table_name="legal_documents")
    op.create_index(
        op.f("ix_legal_documents_document_type"), "legal_documents", ["document_type"], unique=False
    )
    op.create_index(
        op.f("ix_legal_documents_published_at"), "legal_documents", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_legal_documents_status"), "legal_documents", ["status"], unique=False)
    op.alter_column(
        "npo_applications",
        "review_notes",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="Array of review notes with timestamp, reviewer, action, notes",
        existing_nullable=True,
    )
    op.alter_column(
        "npo_branding",
        "primary_color",
        existing_type=sa.VARCHAR(length=7),
        comment="Primary brand color in hex format",
        existing_nullable=True,
    )
    op.alter_column(
        "npo_branding",
        "secondary_color",
        existing_type=sa.VARCHAR(length=7),
        comment="Secondary brand color in hex format",
        existing_nullable=True,
    )
    op.alter_column(
        "npo_branding",
        "logo_url",
        existing_type=sa.VARCHAR(length=500),
        comment="Azure Blob Storage URL for NPO logo",
        existing_nullable=True,
    )
    op.alter_column(
        "npo_branding",
        "social_media_links",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="Social media platform URLs and handles",
        existing_nullable=True,
    )
    op.alter_column(
        "npo_branding",
        "custom_css_properties",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="Additional CSS custom properties for theming",
        existing_nullable=True,
    )
    op.drop_constraint(op.f("npo_branding_npo_id_key"), "npo_branding", type_="unique")
    op.drop_index(op.f("ix_npo_branding_npo_id"), table_name="npo_branding")
    op.create_index(op.f("ix_npo_branding_npo_id"), "npo_branding", ["npo_id"], unique=True)
    op.alter_column(
        "npo_members",
        "joined_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When user accepted invitation and became active member",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_npo_members_npo_status"), table_name="npo_members")
    op.drop_index(op.f("ix_npo_members_user_status"), table_name="npo_members")
    op.execute("DROP INDEX IF EXISTS ix_npos_deleted_at")
    op.drop_constraint(op.f("npos_name_key"), "npos", type_="unique")
    op.drop_index(op.f("ix_npos_name"), table_name="npos")
    op.create_index(op.f("ix_npos_name"), "npos", ["name"], unique=True)
    op.alter_column(
        "roles", "description", existing_type=sa.TEXT(), type_=sa.String(length=255), nullable=True
    )
    op.alter_column(
        "roles",
        "scope",
        existing_type=sa.VARCHAR(length=20),
        comment="Access scope: platform, npo, event, own",
        existing_nullable=False,
    )
    op.alter_column(
        "roles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "roles",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_roles_name"), table_name="roles")
    op.drop_constraint(op.f("roles_name_key"), "roles", type_="unique")
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.drop_index(
        op.f("idx_sessions_active"), table_name="sessions", postgresql_where="(revoked_at IS NULL)"
    )
    op.drop_index(op.f("idx_sessions_created_at"), table_name="sessions")
    op.drop_index(op.f("idx_sessions_expires_at"), table_name="sessions")
    op.drop_index(op.f("idx_sessions_jti"), table_name="sessions")
    op.drop_index(op.f("idx_sessions_user_expires"), table_name="sessions")
    op.drop_index(op.f("idx_sessions_user_id"), table_name="sessions")
    op.drop_constraint(op.f("sessions_refresh_token_jti_key"), "sessions", type_="unique")
    op.create_index(op.f("ix_sessions_created_at"), "sessions", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_sessions_refresh_token_jti"), "sessions", ["refresh_token_jti"], unique=True
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.drop_index(op.f("idx_user_consents_created_at"), table_name="user_consents")
    op.drop_index(op.f("idx_user_consents_status"), table_name="user_consents")
    op.drop_index(op.f("idx_user_consents_user_id"), table_name="user_consents")
    op.create_index(op.f("ix_user_consents_status"), "user_consents", ["status"], unique=False)
    op.create_index(op.f("ix_user_consents_user_id"), "user_consents", ["user_id"], unique=False)
    op.drop_index(op.f("idx_users_created_at"), table_name="users")
    op.drop_index(op.f("idx_users_email"), table_name="users")
    op.drop_index(
        op.f("idx_users_email_verified"),
        table_name="users",
        postgresql_where="(email_verified = false)",
    )
    op.drop_index(
        op.f("idx_users_npo_id"), table_name="users", postgresql_where="(npo_id IS NOT NULL)"
    )
    op.drop_index(
        op.f("idx_users_organization_name"),
        table_name="users",
        postgresql_where="(organization_name IS NOT NULL)",
    )
    op.drop_index(op.f("idx_users_role_id"), table_name="users")
    op.drop_index(op.f("idx_users_role_npo"), table_name="users")
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role_id"), "users", ["role_id"], unique=False)
    op.drop_column("users", "city")
    op.drop_column("users", "state")
    op.drop_column("users", "postal_code")
    op.drop_column("users", "address_line1")
    op.drop_column("users", "country")
    op.drop_column("users", "organization_name")
    op.drop_column("users", "address_line2")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("address_line2", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("organization_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users", sa.Column("country", sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("address_line1", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users", sa.Column("postal_code", sa.VARCHAR(length=20), autoincrement=False, nullable=True)
    )
    op.add_column(
        "users", sa.Column("state", sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.add_column(
        "users", sa.Column("city", sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_users_role_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("idx_users_role_npo"), "users", ["role_id", "npo_id"], unique=False)
    op.create_index(op.f("idx_users_role_id"), "users", ["role_id"], unique=False)
    op.create_index(
        op.f("idx_users_organization_name"),
        "users",
        ["organization_name"],
        unique=False,
        postgresql_where="(organization_name IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_users_npo_id"),
        "users",
        ["npo_id"],
        unique=False,
        postgresql_where="(npo_id IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_users_email_verified"),
        "users",
        ["email_verified"],
        unique=False,
        postgresql_where="(email_verified = false)",
    )
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.create_index(
        op.f("idx_users_created_at"), "users", [sa.literal_column("created_at DESC")], unique=False
    )
    op.drop_index(op.f("ix_user_consents_user_id"), table_name="user_consents")
    op.drop_index(op.f("ix_user_consents_status"), table_name="user_consents")
    op.create_index(op.f("idx_user_consents_user_id"), "user_consents", ["user_id"], unique=False)
    op.create_index(op.f("idx_user_consents_status"), "user_consents", ["status"], unique=False)
    op.create_index(
        op.f("idx_user_consents_created_at"),
        "user_consents",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_refresh_token_jti"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_created_at"), table_name="sessions")
    op.create_unique_constraint(
        op.f("sessions_refresh_token_jti_key"),
        "sessions",
        ["refresh_token_jti"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("idx_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_index(
        op.f("idx_sessions_user_expires"), "sessions", ["user_id", "expires_at"], unique=False
    )
    op.create_index(op.f("idx_sessions_jti"), "sessions", ["refresh_token_jti"], unique=False)
    op.create_index(op.f("idx_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(
        op.f("idx_sessions_created_at"),
        "sessions",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_sessions_active"),
        "sessions",
        ["user_id", "revoked_at"],
        unique=False,
        postgresql_where="(revoked_at IS NULL)",
    )
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.create_unique_constraint(
        op.f("roles_name_key"), "roles", ["name"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("idx_roles_name"), "roles", ["name"], unique=True)
    op.alter_column(
        "roles",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "roles",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "roles",
        "scope",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Access scope: platform, npo, event, own",
        existing_nullable=False,
    )
    op.alter_column(
        "roles", "description", existing_type=sa.String(length=255), type_=sa.TEXT(), nullable=False
    )
    op.drop_index(op.f("ix_npos_name"), table_name="npos")
    op.create_index(op.f("ix_npos_name"), "npos", ["name"], unique=False)
    op.create_unique_constraint(
        op.f("npos_name_key"), "npos", ["name"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("ix_npos_deleted_at"), "npos", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_npo_members_user_status"), "npo_members", ["user_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_npo_members_npo_status"), "npo_members", ["npo_id", "status"], unique=False
    )
    op.alter_column(
        "npo_members",
        "joined_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When user accepted invitation and became active member",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_npo_branding_npo_id"), table_name="npo_branding")
    op.create_index(op.f("ix_npo_branding_npo_id"), "npo_branding", ["npo_id"], unique=False)
    op.create_unique_constraint(
        op.f("npo_branding_npo_id_key"),
        "npo_branding",
        ["npo_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "npo_branding",
        "custom_css_properties",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment="Additional CSS custom properties for theming",
        existing_nullable=True,
    )
    op.alter_column(
        "npo_branding",
        "social_media_links",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment="Social media platform URLs and handles",
        existing_nullable=True,
    )
    op.alter_column(
        "npo_branding",
        "logo_url",
        existing_type=sa.VARCHAR(length=500),
        comment=None,
        existing_comment="Azure Blob Storage URL for NPO logo",
        existing_nullable=True,
    )
    op.alter_column(
        "npo_branding",
        "secondary_color",
        existing_type=sa.VARCHAR(length=7),
        comment=None,
        existing_comment="Secondary brand color in hex format",
        existing_nullable=True,
    )
    op.alter_column(
        "npo_branding",
        "primary_color",
        existing_type=sa.VARCHAR(length=7),
        comment=None,
        existing_comment="Primary brand color in hex format",
        existing_nullable=True,
    )
    op.alter_column(
        "npo_applications",
        "review_notes",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment="Array of review notes with timestamp, reviewer, action, notes",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_legal_documents_status"), table_name="legal_documents")
    op.drop_index(op.f("ix_legal_documents_published_at"), table_name="legal_documents")
    op.drop_index(op.f("ix_legal_documents_document_type"), table_name="legal_documents")
    op.create_index(
        op.f("idx_legal_documents_type_version"),
        "legal_documents",
        ["document_type", "version"],
        unique=True,
    )
    op.create_index(op.f("idx_legal_documents_status"), "legal_documents", ["status"], unique=False)
    op.create_index(
        op.f("idx_legal_documents_published_at"),
        "legal_documents",
        [sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.drop_index(op.f("ix_invitations_token_hash"), table_name="invitations")
    op.create_index(op.f("ix_invitations_token_hash"), "invitations", ["token_hash"], unique=False)
    op.create_index(
        op.f("ix_invitations_npo_status"), "invitations", ["npo_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_invitations_email_status"), "invitations", ["email", "status"], unique=False
    )
    op.create_unique_constraint(
        op.f("invitations_token_hash_key"),
        "invitations",
        ["token_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "invitations",
        "accepted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When invitation was accepted",
        existing_nullable=True,
    )
    op.alter_column(
        "invitations",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Invitation expiry (7 days from creation)",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "token_hash",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Hashed JWT invitation token",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "status",
        existing_type=sa.Enum(
            "pending", "accepted", "expired", "revoked", name="invitation_status", native_enum=False
        ),
        type_=postgresql.ENUM(
            "pending", "accepted", "expired", "revoked", name="invitation_status"
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::invitation_status"),
    )
    op.alter_column(
        "invitations",
        "role",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Role to assign: admin, co_admin, or staff",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "last_name",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Optional last name to pre-fill registration",
        existing_nullable=True,
    )
    op.alter_column(
        "invitations",
        "first_name",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Optional first name to pre-fill registration",
        existing_nullable=True,
    )
    op.alter_column(
        "invitations",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Invitation target email address",
        existing_nullable=False,
    )
    op.alter_column(
        "invitations",
        "invited_user_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Set when existing user is invited",
        existing_nullable=True,
    )
    op.create_index(
        op.f("idx_food_options_display_order"),
        "food_options",
        ["event_id", "display_order"],
        unique=False,
    )
    op.alter_column(
        "food_options",
        "description",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Optional detailed description",
        existing_nullable=True,
    )
    op.alter_column(
        "food_options",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Option name (e.g., 'Chicken', 'Vegetarian')",
        existing_nullable=False,
    )
    op.alter_column(
        "events",
        "version",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Version counter for optimistic locking",
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "events",
        "secondary_color",
        existing_type=sa.VARCHAR(length=7),
        comment=None,
        existing_comment="Hex color code (e.g., #33C4FF)",
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "primary_color",
        existing_type=sa.VARCHAR(length=7),
        comment=None,
        existing_comment="Hex color code (e.g., #FF5733)",
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "logo_url",
        existing_type=sa.VARCHAR(length=500),
        comment=None,
        existing_comment="Event-specific logo (Azure Blob URL)",
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "description",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Rich text description (Markdown format)",
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "timezone",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="IANA timezone name (e.g., America/Chicago)",
        existing_nullable=False,
    )
    op.create_index(
        op.f("idx_event_media_display_order"),
        "event_media",
        ["event_id", "display_order"],
        unique=False,
    )
    op.alter_column(
        "event_media",
        "display_order",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Order for gallery display",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "event_media",
        "file_size",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="File size in bytes",
        existing_nullable=False,
    )
    op.alter_column(
        "event_media",
        "file_type",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="MIME type (e.g., image/png)",
        existing_nullable=False,
    )
    op.alter_column(
        "event_media",
        "file_name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Original filename",
        existing_nullable=False,
    )
    op.alter_column(
        "event_media",
        "file_url",
        existing_type=sa.VARCHAR(length=500),
        comment=None,
        existing_comment="Azure Blob Storage URL",
        existing_nullable=False,
    )
    op.drop_column("event_media", "blob_name")
    op.drop_column("event_media", "mime_type")
    op.drop_column("event_media", "media_type")
    # Drop event_media_type enum
    op.execute("DROP TYPE IF EXISTS event_media_type")
    op.create_index(
        op.f("idx_event_links_link_type"), "event_links", ["event_id", "link_type"], unique=False
    )
    op.alter_column(
        "event_links",
        "platform",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Platform name (YouTube, Vimeo, Facebook, etc.)",
        existing_nullable=True,
    )
    op.alter_column(
        "event_links",
        "label",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Display label (e.g., 'Event Promo Video')",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_cookie_consents_user_id"), table_name="cookie_consents")
    op.drop_index(op.f("ix_cookie_consents_session_id"), table_name="cookie_consents")
    op.create_index(
        op.f("idx_cookie_consents_user_id"), "cookie_consents", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_cookie_consents_session_id"), "cookie_consents", ["session_id"], unique=False
    )
    op.create_index(
        op.f("idx_cookie_consents_created_at"),
        "cookie_consents",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index(op.f("ix_consent_audit_logs_user_id"), table_name="consent_audit_logs")
    op.drop_index(op.f("ix_consent_audit_logs_created_at"), table_name="consent_audit_logs")
    op.drop_index(op.f("ix_consent_audit_logs_action"), table_name="consent_audit_logs")
    op.create_index(
        op.f("idx_consent_audit_logs_user_id"), "consent_audit_logs", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_consent_audit_logs_details_gin"),
        "consent_audit_logs",
        ["details"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_consent_audit_logs_created_at"),
        "consent_audit_logs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_consent_audit_logs_action"), "consent_audit_logs", ["action"], unique=False
    )
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_ip_address"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.create_index(op.f("idx_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_index(
        op.f("idx_audit_logs_user_created"),
        "audit_logs",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_audit_logs_metadata_gin"),
        "audit_logs",
        ["metadata"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("idx_audit_logs_ip_address"), "audit_logs", ["ip_address"], unique=False)
    op.create_index(
        op.f("idx_audit_logs_created_at"),
        "audit_logs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_audit_logs_action_created"),
        "audit_logs",
        ["action", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(op.f("idx_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_table(
        "testimonials",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("quote_text", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("author_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("author_role", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("organization_name", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.Column("photo_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column(
            "display_order",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_published",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("testimonials_created_by_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("testimonials_pkey")),
    )
    op.create_index(
        op.f("idx_testimonials_role"),
        "testimonials",
        ["author_role"],
        unique=False,
        postgresql_where="((deleted_at IS NULL) AND (is_published = true))",
    )
    op.create_index(
        op.f("idx_testimonials_published_order"),
        "testimonials",
        ["is_published", "display_order"],
        unique=False,
        postgresql_where="(deleted_at IS NULL)",
    )
    op.create_index(
        op.f("idx_testimonials_created_by"), "testimonials", ["created_by"], unique=False
    )
    op.create_table(
        "contact_submissions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("sender_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("sender_email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("subject", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("pending", "processed", "failed", name="submissionstatus"),
            server_default=sa.text("'pending'::submissionstatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("contact_submissions_pkey")),
    )
    op.create_index(
        op.f("idx_contact_submissions_status"), "contact_submissions", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_contact_submissions_ip_created"),
        "contact_submissions",
        ["ip_address", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_contact_submissions_created_at"),
        "contact_submissions",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
