"""add auction_bid_import_batches table

Revision ID: d4f5e6a7b8c9
Revises: 8202f93bb2fb
Create Date: 2026-02-07 19:03:00.000000

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "d4f5e6a7b8c9"
down_revision = "8202f93bb2fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auction_bid_import_batches",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "event_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "initiated_by_user_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("valid_rows", sa.Integer(), nullable=False),
        sa.Column("invalid_rows", sa.Integer(), nullable=False),
        sa.Column("created_bids", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column("validation_errors", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("import_notes", sa.Text(), nullable=True),
        sa.Column("preflighted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('preflighted', 'completed', 'failed')",
            name="ck_auction_bid_import_batches_status",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_auction_bid_import_batches_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["initiated_by_user_id"],
            ["users.id"],
            name=op.f("fk_auction_bid_import_batches_initiated_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auction_bid_import_batches")),
    )
    op.create_index(
        op.f("ix_auction_bid_import_batches_event_id"),
        "auction_bid_import_batches",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auction_bid_import_batches_initiated_by_user_id"),
        "auction_bid_import_batches",
        ["initiated_by_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_auction_bid_import_batches_initiated_by_user_id"),
        table_name="auction_bid_import_batches",
    )
    op.drop_index(
        op.f("ix_auction_bid_import_batches_event_id"), table_name="auction_bid_import_batches"
    )
    op.drop_table("auction_bid_import_batches")
    # ### end Alembic commands ###
