/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DonorPortalRedirectRouteImport } from './routes/donor-portal-redirect'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations/accept'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authTermsOfServiceRouteImport } from './routes/(auth)/terms-of-service'
import { Route as authSocialCallbackRouteImport } from './routes/(auth)/social-callback'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authPrivacyPolicyRouteImport } from './routes/(auth)/privacy-policy'
import { Route as authPasswordResetConfirmRouteImport } from './routes/(auth)/password-reset-confirm'
import { Route as authPasswordResetRouteImport } from './routes/(auth)/password-reset'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authCompleteProfileRouteImport } from './routes/(auth)/complete-profile'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedEventsRouteRouteImport } from './routes/_authenticated/events/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedNposIndexRouteImport } from './routes/_authenticated/npos/index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as authRegisterNpoIndexRouteImport } from './routes/(auth)/register-npo/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsSupportRouteImport } from './routes/_authenticated/settings/support'
import { Route as AuthenticatedSettingsPasswordRouteImport } from './routes/_authenticated/settings/password'
import { Route as AuthenticatedSettingsConsentRouteImport } from './routes/_authenticated/settings/consent'
import { Route as AuthenticatedNposCreateRouteImport } from './routes/_authenticated/npos/create'
import { Route as AuthenticatedEventsCreateRouteImport } from './routes/_authenticated/events/create'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAdminNpoApplicationsRouteImport } from './routes/_authenticated/admin/npo-applications'
import { Route as AuthenticatedEventsEventIdRouteRouteImport } from './routes/_authenticated/events/$eventId/route'
import { Route as AuthenticatedUsersUserIdIndexRouteImport } from './routes/_authenticated/users/$userId/index'
import { Route as AuthenticatedNposNpoIdIndexRouteImport } from './routes/_authenticated/npos/$npoId.index'
import { Route as AuthenticatedEventsEventIdIndexRouteImport } from './routes/_authenticated/events/$eventId/index'
import { Route as AuthenticatedNposNpoIdPaymentSettingsRouteImport } from './routes/_authenticated/npos/$npoId/payment-settings'
import { Route as AuthenticatedNposNpoIdEditRouteImport } from './routes/_authenticated/npos/$npoId/edit'
import { Route as AuthenticatedEventsEventIdTicketsRouteImport } from './routes/_authenticated/events/$eventId/tickets'
import { Route as AuthenticatedEventsEventIdSponsorsRouteImport } from './routes/_authenticated/events/$eventId/sponsors'
import { Route as AuthenticatedEventsEventIdSeatingRouteImport } from './routes/_authenticated/events/$eventId/seating'
import { Route as AuthenticatedEventsEventIdRegistrationsRouteImport } from './routes/_authenticated/events/$eventId/registrations'
import { Route as AuthenticatedEventsEventIdQuickEntryRouteImport } from './routes/_authenticated/events/$eventId/quick-entry'
import { Route as AuthenticatedEventsEventIdPreviewRouteImport } from './routes/_authenticated/events/$eventId/preview'
import { Route as AuthenticatedEventsEventIdPaymentsRouteImport } from './routes/_authenticated/events/$eventId/payments'
import { Route as AuthenticatedEventsEventIdNotificationsRouteImport } from './routes/_authenticated/events/$eventId/notifications'
import { Route as AuthenticatedEventsEventIdMediaRouteImport } from './routes/_authenticated/events/$eventId/media'
import { Route as AuthenticatedEventsEventIdLinksRouteImport } from './routes/_authenticated/events/$eventId/links'
import { Route as AuthenticatedEventsEventIdFoodRouteImport } from './routes/_authenticated/events/$eventId/food'
import { Route as AuthenticatedEventsEventIdEditRouteImport } from './routes/_authenticated/events/$eventId/edit'
import { Route as AuthenticatedEventsEventIdDetailsRouteImport } from './routes/_authenticated/events/$eventId/details'
import { Route as AuthenticatedEventsEventIdDashboardRouteImport } from './routes/_authenticated/events/$eventId/dashboard'
import { Route as AuthenticatedEventsEventIdChecklistRouteImport } from './routes/_authenticated/events/$eventId/checklist'
import { Route as AuthenticatedEventsEventIdCheckinRouteImport } from './routes/_authenticated/events/$eventId/checkin'
import { Route as AuthenticatedEventsEventIdAuctionItemsRouteImport } from './routes/_authenticated/events/$eventId/auction-items'
import { Route as AuthenticatedEventsEventIdAuctionBidsRouteImport } from './routes/_authenticated/events/$eventId/auction-bids'
import { Route as AuthenticatedEventsEventIdTicketsIndexRouteImport } from './routes/_authenticated/events/$eventId/tickets/index'
import { Route as AuthenticatedEventsEventIdAuctionItemsIndexRouteImport } from './routes/_authenticated/events/$eventId/auction-items/index'
import { Route as AuthenticatedEventsEventIdTicketsSalesRouteImport } from './routes/_authenticated/events/$eventId/tickets/sales'
import { Route as AuthenticatedEventsEventIdTicketsPromosRouteImport } from './routes/_authenticated/events/$eventId/tickets/promos'
import { Route as AuthenticatedEventsEventIdTicketsCreateRouteImport } from './routes/_authenticated/events/$eventId/tickets/create'
import { Route as AuthenticatedEventsEventIdAuctionItemsCreateRouteImport } from './routes/_authenticated/events/$eventId/auction-items/create'
import { Route as AuthenticatedEventsEventIdAuctionItemsItemIdIndexRouteImport } from './routes/_authenticated/events/$eventId/auction-items/$itemId/index'
import { Route as AuthenticatedEventsEventIdTicketsPackageIdEditRouteImport } from './routes/_authenticated/events/$eventId/tickets/$packageId/edit'
import { Route as AuthenticatedEventsEventIdAuctionItemsItemIdEngagementRouteImport } from './routes/_authenticated/events/$eventId/auction-items/$itemId/engagement'
import { Route as AuthenticatedEventsEventIdAuctionItemsItemIdEditRouteImport } from './routes/_authenticated/events/$eventId/auction-items/$itemId/edit'

const DonorPortalRedirectRoute = DonorPortalRedirectRouteImport.update({
  id: '/donor-portal-redirect',
  path: '/donor-portal-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authTermsOfServiceRoute = authTermsOfServiceRouteImport.update({
  id: '/(auth)/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const authSocialCallbackRoute = authSocialCallbackRouteImport.update({
  id: '/(auth)/social-callback',
  path: '/social-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authPrivacyPolicyRoute = authPrivacyPolicyRouteImport.update({
  id: '/(auth)/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const authPasswordResetConfirmRoute =
  authPasswordResetConfirmRouteImport.update({
    id: '/(auth)/password-reset-confirm',
    path: '/password-reset-confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const authPasswordResetRoute = authPasswordResetRouteImport.update({
  id: '/(auth)/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authCompleteProfileRoute = authCompleteProfileRouteImport.update({
  id: '/(auth)/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsRouteRoute =
  AuthenticatedEventsRouteRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedNposIndexRoute = AuthenticatedNposIndexRouteImport.update({
  id: '/npos/',
  path: '/npos/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEventsRouteRoute,
  } as any)
const authRegisterNpoIndexRoute = authRegisterNpoIndexRouteImport.update({
  id: '/(auth)/register-npo/',
  path: '/register-npo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsSupportRoute =
  AuthenticatedSettingsSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsPasswordRoute =
  AuthenticatedSettingsPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsConsentRoute =
  AuthenticatedSettingsConsentRouteImport.update({
    id: '/consent',
    path: '/consent',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedNposCreateRoute = AuthenticatedNposCreateRouteImport.update({
  id: '/npos/create',
  path: '/npos/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsCreateRoute =
  AuthenticatedEventsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedEventsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNpoApplicationsRoute =
  AuthenticatedAdminNpoApplicationsRouteImport.update({
    id: '/admin/npo-applications',
    path: '/admin/npo-applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventIdRouteRoute =
  AuthenticatedEventsEventIdRouteRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => AuthenticatedEventsRouteRoute,
  } as any)
const AuthenticatedUsersUserIdIndexRoute =
  AuthenticatedUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNposNpoIdIndexRoute =
  AuthenticatedNposNpoIdIndexRouteImport.update({
    id: '/npos/$npoId/',
    path: '/npos/$npoId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventIdIndexRoute =
  AuthenticatedEventsEventIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedNposNpoIdPaymentSettingsRoute =
  AuthenticatedNposNpoIdPaymentSettingsRouteImport.update({
    id: '/npos/$npoId/payment-settings',
    path: '/npos/$npoId/payment-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNposNpoIdEditRoute =
  AuthenticatedNposNpoIdEditRouteImport.update({
    id: '/npos/$npoId/edit',
    path: '/npos/$npoId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventIdTicketsRoute =
  AuthenticatedEventsEventIdTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdSponsorsRoute =
  AuthenticatedEventsEventIdSponsorsRouteImport.update({
    id: '/sponsors',
    path: '/sponsors',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdSeatingRoute =
  AuthenticatedEventsEventIdSeatingRouteImport.update({
    id: '/seating',
    path: '/seating',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdRegistrationsRoute =
  AuthenticatedEventsEventIdRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdQuickEntryRoute =
  AuthenticatedEventsEventIdQuickEntryRouteImport.update({
    id: '/quick-entry',
    path: '/quick-entry',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdPreviewRoute =
  AuthenticatedEventsEventIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdPaymentsRoute =
  AuthenticatedEventsEventIdPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdNotificationsRoute =
  AuthenticatedEventsEventIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdMediaRoute =
  AuthenticatedEventsEventIdMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdLinksRoute =
  AuthenticatedEventsEventIdLinksRouteImport.update({
    id: '/links',
    path: '/links',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdFoodRoute =
  AuthenticatedEventsEventIdFoodRouteImport.update({
    id: '/food',
    path: '/food',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdEditRoute =
  AuthenticatedEventsEventIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdDetailsRoute =
  AuthenticatedEventsEventIdDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdDashboardRoute =
  AuthenticatedEventsEventIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdChecklistRoute =
  AuthenticatedEventsEventIdChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdCheckinRoute =
  AuthenticatedEventsEventIdCheckinRouteImport.update({
    id: '/checkin',
    path: '/checkin',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdAuctionItemsRoute =
  AuthenticatedEventsEventIdAuctionItemsRouteImport.update({
    id: '/auction-items',
    path: '/auction-items',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdAuctionBidsRoute =
  AuthenticatedEventsEventIdAuctionBidsRouteImport.update({
    id: '/auction-bids',
    path: '/auction-bids',
    getParentRoute: () => AuthenticatedEventsEventIdRouteRoute,
  } as any)
const AuthenticatedEventsEventIdTicketsIndexRoute =
  AuthenticatedEventsEventIdTicketsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEventsEventIdTicketsRoute,
  } as any)
const AuthenticatedEventsEventIdAuctionItemsIndexRoute =
  AuthenticatedEventsEventIdAuctionItemsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEventsEventIdAuctionItemsRoute,
  } as any)
const AuthenticatedEventsEventIdTicketsSalesRoute =
  AuthenticatedEventsEventIdTicketsSalesRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => AuthenticatedEventsEventIdTicketsRoute,
  } as any)
const AuthenticatedEventsEventIdTicketsPromosRoute =
  AuthenticatedEventsEventIdTicketsPromosRouteImport.update({
    id: '/promos',
    path: '/promos',
    getParentRoute: () => AuthenticatedEventsEventIdTicketsRoute,
  } as any)
const AuthenticatedEventsEventIdTicketsCreateRoute =
  AuthenticatedEventsEventIdTicketsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedEventsEventIdTicketsRoute,
  } as any)
const AuthenticatedEventsEventIdAuctionItemsCreateRoute =
  AuthenticatedEventsEventIdAuctionItemsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedEventsEventIdAuctionItemsRoute,
  } as any)
const AuthenticatedEventsEventIdAuctionItemsItemIdIndexRoute =
  AuthenticatedEventsEventIdAuctionItemsItemIdIndexRouteImport.update({
    id: '/$itemId/',
    path: '/$itemId/',
    getParentRoute: () => AuthenticatedEventsEventIdAuctionItemsRoute,
  } as any)
const AuthenticatedEventsEventIdTicketsPackageIdEditRoute =
  AuthenticatedEventsEventIdTicketsPackageIdEditRouteImport.update({
    id: '/$packageId/edit',
    path: '/$packageId/edit',
    getParentRoute: () => AuthenticatedEventsEventIdTicketsRoute,
  } as any)
const AuthenticatedEventsEventIdAuctionItemsItemIdEngagementRoute =
  AuthenticatedEventsEventIdAuctionItemsItemIdEngagementRouteImport.update({
    id: '/$itemId/engagement',
    path: '/$itemId/engagement',
    getParentRoute: () => AuthenticatedEventsEventIdAuctionItemsRoute,
  } as any)
const AuthenticatedEventsEventIdAuctionItemsItemIdEditRoute =
  AuthenticatedEventsEventIdAuctionItemsItemIdEditRouteImport.update({
    id: '/$itemId/edit',
    path: '/$itemId/edit',
    getParentRoute: () => AuthenticatedEventsEventIdAuctionItemsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/donor-portal-redirect': typeof DonorPortalRedirectRoute
  '/events': typeof AuthenticatedEventsRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/complete-profile': typeof authCompleteProfileRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/password-reset': typeof authPasswordResetRoute
  '/password-reset-confirm': typeof authPasswordResetConfirmRoute
  '/privacy-policy': typeof authPrivacyPolicyRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/social-callback': typeof authSocialCallbackRoute
  '/terms-of-service': typeof authTermsOfServiceRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRouteRouteWithChildren
  '/admin/npo-applications': typeof AuthenticatedAdminNpoApplicationsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/events/create': typeof AuthenticatedEventsCreateRoute
  '/npos/create': typeof AuthenticatedNposCreateRoute
  '/settings/consent': typeof AuthenticatedSettingsConsentRoute
  '/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/settings/support': typeof AuthenticatedSettingsSupportRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/register-npo/': typeof authRegisterNpoIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/npos/': typeof AuthenticatedNposIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/events/$eventId/auction-bids': typeof AuthenticatedEventsEventIdAuctionBidsRoute
  '/events/$eventId/auction-items': typeof AuthenticatedEventsEventIdAuctionItemsRouteWithChildren
  '/events/$eventId/checkin': typeof AuthenticatedEventsEventIdCheckinRoute
  '/events/$eventId/checklist': typeof AuthenticatedEventsEventIdChecklistRoute
  '/events/$eventId/dashboard': typeof AuthenticatedEventsEventIdDashboardRoute
  '/events/$eventId/details': typeof AuthenticatedEventsEventIdDetailsRoute
  '/events/$eventId/edit': typeof AuthenticatedEventsEventIdEditRoute
  '/events/$eventId/food': typeof AuthenticatedEventsEventIdFoodRoute
  '/events/$eventId/links': typeof AuthenticatedEventsEventIdLinksRoute
  '/events/$eventId/media': typeof AuthenticatedEventsEventIdMediaRoute
  '/events/$eventId/notifications': typeof AuthenticatedEventsEventIdNotificationsRoute
  '/events/$eventId/payments': typeof AuthenticatedEventsEventIdPaymentsRoute
  '/events/$eventId/preview': typeof AuthenticatedEventsEventIdPreviewRoute
  '/events/$eventId/quick-entry': typeof AuthenticatedEventsEventIdQuickEntryRoute
  '/events/$eventId/registrations': typeof AuthenticatedEventsEventIdRegistrationsRoute
  '/events/$eventId/seating': typeof AuthenticatedEventsEventIdSeatingRoute
  '/events/$eventId/sponsors': typeof AuthenticatedEventsEventIdSponsorsRoute
  '/events/$eventId/tickets': typeof AuthenticatedEventsEventIdTicketsRouteWithChildren
  '/npos/$npoId/edit': typeof AuthenticatedNposNpoIdEditRoute
  '/npos/$npoId/payment-settings': typeof AuthenticatedNposNpoIdPaymentSettingsRoute
  '/events/$eventId/': typeof AuthenticatedEventsEventIdIndexRoute
  '/npos/$npoId/': typeof AuthenticatedNposNpoIdIndexRoute
  '/users/$userId/': typeof AuthenticatedUsersUserIdIndexRoute
  '/events/$eventId/auction-items/create': typeof AuthenticatedEventsEventIdAuctionItemsCreateRoute
  '/events/$eventId/tickets/create': typeof AuthenticatedEventsEventIdTicketsCreateRoute
  '/events/$eventId/tickets/promos': typeof AuthenticatedEventsEventIdTicketsPromosRoute
  '/events/$eventId/tickets/sales': typeof AuthenticatedEventsEventIdTicketsSalesRoute
  '/events/$eventId/auction-items/': typeof AuthenticatedEventsEventIdAuctionItemsIndexRoute
  '/events/$eventId/tickets/': typeof AuthenticatedEventsEventIdTicketsIndexRoute
  '/events/$eventId/auction-items/$itemId/edit': typeof AuthenticatedEventsEventIdAuctionItemsItemIdEditRoute
  '/events/$eventId/auction-items/$itemId/engagement': typeof AuthenticatedEventsEventIdAuctionItemsItemIdEngagementRoute
  '/events/$eventId/tickets/$packageId/edit': typeof AuthenticatedEventsEventIdTicketsPackageIdEditRoute
  '/events/$eventId/auction-items/$itemId/': typeof AuthenticatedEventsEventIdAuctionItemsItemIdIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/donor-portal-redirect': typeof DonorPortalRedirectRoute
  '/complete-profile': typeof authCompleteProfileRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/password-reset': typeof authPasswordResetRoute
  '/password-reset-confirm': typeof authPasswordResetConfirmRoute
  '/privacy-policy': typeof authPrivacyPolicyRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/social-callback': typeof authSocialCallbackRoute
  '/terms-of-service': typeof authTermsOfServiceRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/npo-applications': typeof AuthenticatedAdminNpoApplicationsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/events/create': typeof AuthenticatedEventsCreateRoute
  '/npos/create': typeof AuthenticatedNposCreateRoute
  '/settings/consent': typeof AuthenticatedSettingsConsentRoute
  '/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/settings/support': typeof AuthenticatedSettingsSupportRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/register-npo': typeof authRegisterNpoIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/npos': typeof AuthenticatedNposIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/events/$eventId/auction-bids': typeof AuthenticatedEventsEventIdAuctionBidsRoute
  '/events/$eventId/checkin': typeof AuthenticatedEventsEventIdCheckinRoute
  '/events/$eventId/checklist': typeof AuthenticatedEventsEventIdChecklistRoute
  '/events/$eventId/dashboard': typeof AuthenticatedEventsEventIdDashboardRoute
  '/events/$eventId/details': typeof AuthenticatedEventsEventIdDetailsRoute
  '/events/$eventId/edit': typeof AuthenticatedEventsEventIdEditRoute
  '/events/$eventId/food': typeof AuthenticatedEventsEventIdFoodRoute
  '/events/$eventId/links': typeof AuthenticatedEventsEventIdLinksRoute
  '/events/$eventId/media': typeof AuthenticatedEventsEventIdMediaRoute
  '/events/$eventId/notifications': typeof AuthenticatedEventsEventIdNotificationsRoute
  '/events/$eventId/payments': typeof AuthenticatedEventsEventIdPaymentsRoute
  '/events/$eventId/preview': typeof AuthenticatedEventsEventIdPreviewRoute
  '/events/$eventId/quick-entry': typeof AuthenticatedEventsEventIdQuickEntryRoute
  '/events/$eventId/registrations': typeof AuthenticatedEventsEventIdRegistrationsRoute
  '/events/$eventId/seating': typeof AuthenticatedEventsEventIdSeatingRoute
  '/events/$eventId/sponsors': typeof AuthenticatedEventsEventIdSponsorsRoute
  '/npos/$npoId/edit': typeof AuthenticatedNposNpoIdEditRoute
  '/npos/$npoId/payment-settings': typeof AuthenticatedNposNpoIdPaymentSettingsRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdIndexRoute
  '/npos/$npoId': typeof AuthenticatedNposNpoIdIndexRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdIndexRoute
  '/events/$eventId/auction-items/create': typeof AuthenticatedEventsEventIdAuctionItemsCreateRoute
  '/events/$eventId/tickets/create': typeof AuthenticatedEventsEventIdTicketsCreateRoute
  '/events/$eventId/tickets/promos': typeof AuthenticatedEventsEventIdTicketsPromosRoute
  '/events/$eventId/tickets/sales': typeof AuthenticatedEventsEventIdTicketsSalesRoute
  '/events/$eventId/auction-items': typeof AuthenticatedEventsEventIdAuctionItemsIndexRoute
  '/events/$eventId/tickets': typeof AuthenticatedEventsEventIdTicketsIndexRoute
  '/events/$eventId/auction-items/$itemId/edit': typeof AuthenticatedEventsEventIdAuctionItemsItemIdEditRoute
  '/events/$eventId/auction-items/$itemId/engagement': typeof AuthenticatedEventsEventIdAuctionItemsItemIdEngagementRoute
  '/events/$eventId/tickets/$packageId/edit': typeof AuthenticatedEventsEventIdTicketsPackageIdEditRoute
  '/events/$eventId/auction-items/$itemId': typeof AuthenticatedEventsEventIdAuctionItemsItemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/donor-portal-redirect': typeof DonorPortalRedirectRoute
  '/_authenticated/events': typeof AuthenticatedEventsRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/complete-profile': typeof authCompleteProfileRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/password-reset': typeof authPasswordResetRoute
  '/(auth)/password-reset-confirm': typeof authPasswordResetConfirmRoute
  '/(auth)/privacy-policy': typeof authPrivacyPolicyRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/social-callback': typeof authSocialCallbackRoute
  '/(auth)/terms-of-service': typeof authTermsOfServiceRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRouteRouteWithChildren
  '/_authenticated/admin/npo-applications': typeof AuthenticatedAdminNpoApplicationsRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/events/create': typeof AuthenticatedEventsCreateRoute
  '/_authenticated/npos/create': typeof AuthenticatedNposCreateRoute
  '/_authenticated/settings/consent': typeof AuthenticatedSettingsConsentRoute
  '/_authenticated/settings/password': typeof AuthenticatedSettingsPasswordRoute
  '/_authenticated/settings/support': typeof AuthenticatedSettingsSupportRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/(auth)/register-npo/': typeof authRegisterNpoIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/npos/': typeof AuthenticatedNposIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/events/$eventId/auction-bids': typeof AuthenticatedEventsEventIdAuctionBidsRoute
  '/_authenticated/events/$eventId/auction-items': typeof AuthenticatedEventsEventIdAuctionItemsRouteWithChildren
  '/_authenticated/events/$eventId/checkin': typeof AuthenticatedEventsEventIdCheckinRoute
  '/_authenticated/events/$eventId/checklist': typeof AuthenticatedEventsEventIdChecklistRoute
  '/_authenticated/events/$eventId/dashboard': typeof AuthenticatedEventsEventIdDashboardRoute
  '/_authenticated/events/$eventId/details': typeof AuthenticatedEventsEventIdDetailsRoute
  '/_authenticated/events/$eventId/edit': typeof AuthenticatedEventsEventIdEditRoute
  '/_authenticated/events/$eventId/food': typeof AuthenticatedEventsEventIdFoodRoute
  '/_authenticated/events/$eventId/links': typeof AuthenticatedEventsEventIdLinksRoute
  '/_authenticated/events/$eventId/media': typeof AuthenticatedEventsEventIdMediaRoute
  '/_authenticated/events/$eventId/notifications': typeof AuthenticatedEventsEventIdNotificationsRoute
  '/_authenticated/events/$eventId/payments': typeof AuthenticatedEventsEventIdPaymentsRoute
  '/_authenticated/events/$eventId/preview': typeof AuthenticatedEventsEventIdPreviewRoute
  '/_authenticated/events/$eventId/quick-entry': typeof AuthenticatedEventsEventIdQuickEntryRoute
  '/_authenticated/events/$eventId/registrations': typeof AuthenticatedEventsEventIdRegistrationsRoute
  '/_authenticated/events/$eventId/seating': typeof AuthenticatedEventsEventIdSeatingRoute
  '/_authenticated/events/$eventId/sponsors': typeof AuthenticatedEventsEventIdSponsorsRoute
  '/_authenticated/events/$eventId/tickets': typeof AuthenticatedEventsEventIdTicketsRouteWithChildren
  '/_authenticated/npos/$npoId/edit': typeof AuthenticatedNposNpoIdEditRoute
  '/_authenticated/npos/$npoId/payment-settings': typeof AuthenticatedNposNpoIdPaymentSettingsRoute
  '/_authenticated/events/$eventId/': typeof AuthenticatedEventsEventIdIndexRoute
  '/_authenticated/npos/$npoId/': typeof AuthenticatedNposNpoIdIndexRoute
  '/_authenticated/users/$userId/': typeof AuthenticatedUsersUserIdIndexRoute
  '/_authenticated/events/$eventId/auction-items/create': typeof AuthenticatedEventsEventIdAuctionItemsCreateRoute
  '/_authenticated/events/$eventId/tickets/create': typeof AuthenticatedEventsEventIdTicketsCreateRoute
  '/_authenticated/events/$eventId/tickets/promos': typeof AuthenticatedEventsEventIdTicketsPromosRoute
  '/_authenticated/events/$eventId/tickets/sales': typeof AuthenticatedEventsEventIdTicketsSalesRoute
  '/_authenticated/events/$eventId/auction-items/': typeof AuthenticatedEventsEventIdAuctionItemsIndexRoute
  '/_authenticated/events/$eventId/tickets/': typeof AuthenticatedEventsEventIdTicketsIndexRoute
  '/_authenticated/events/$eventId/auction-items/$itemId/edit': typeof AuthenticatedEventsEventIdAuctionItemsItemIdEditRoute
  '/_authenticated/events/$eventId/auction-items/$itemId/engagement': typeof AuthenticatedEventsEventIdAuctionItemsItemIdEngagementRoute
  '/_authenticated/events/$eventId/tickets/$packageId/edit': typeof AuthenticatedEventsEventIdTicketsPackageIdEditRoute
  '/_authenticated/events/$eventId/auction-items/$itemId/': typeof AuthenticatedEventsEventIdAuctionItemsItemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/donor-portal-redirect'
    | '/events'
    | '/settings'
    | '/complete-profile'
    | '/forgot-password'
    | '/otp'
    | '/password-reset'
    | '/password-reset-confirm'
    | '/privacy-policy'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/social-callback'
    | '/terms-of-service'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/invitations/accept'
    | '/events/$eventId'
    | '/admin/npo-applications'
    | '/errors/$error'
    | '/events/create'
    | '/npos/create'
    | '/settings/consent'
    | '/settings/password'
    | '/settings/support'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/register-npo/'
    | '/events/'
    | '/npos/'
    | '/settings/'
    | '/users/'
    | '/events/$eventId/auction-bids'
    | '/events/$eventId/auction-items'
    | '/events/$eventId/checkin'
    | '/events/$eventId/checklist'
    | '/events/$eventId/dashboard'
    | '/events/$eventId/details'
    | '/events/$eventId/edit'
    | '/events/$eventId/food'
    | '/events/$eventId/links'
    | '/events/$eventId/media'
    | '/events/$eventId/notifications'
    | '/events/$eventId/payments'
    | '/events/$eventId/preview'
    | '/events/$eventId/quick-entry'
    | '/events/$eventId/registrations'
    | '/events/$eventId/seating'
    | '/events/$eventId/sponsors'
    | '/events/$eventId/tickets'
    | '/npos/$npoId/edit'
    | '/npos/$npoId/payment-settings'
    | '/events/$eventId/'
    | '/npos/$npoId/'
    | '/users/$userId/'
    | '/events/$eventId/auction-items/create'
    | '/events/$eventId/tickets/create'
    | '/events/$eventId/tickets/promos'
    | '/events/$eventId/tickets/sales'
    | '/events/$eventId/auction-items/'
    | '/events/$eventId/tickets/'
    | '/events/$eventId/auction-items/$itemId/edit'
    | '/events/$eventId/auction-items/$itemId/engagement'
    | '/events/$eventId/tickets/$packageId/edit'
    | '/events/$eventId/auction-items/$itemId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/donor-portal-redirect'
    | '/complete-profile'
    | '/forgot-password'
    | '/otp'
    | '/password-reset'
    | '/password-reset-confirm'
    | '/privacy-policy'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/social-callback'
    | '/terms-of-service'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/invitations/accept'
    | '/'
    | '/admin/npo-applications'
    | '/errors/$error'
    | '/events/create'
    | '/npos/create'
    | '/settings/consent'
    | '/settings/password'
    | '/settings/support'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/register-npo'
    | '/events'
    | '/npos'
    | '/settings'
    | '/users'
    | '/events/$eventId/auction-bids'
    | '/events/$eventId/checkin'
    | '/events/$eventId/checklist'
    | '/events/$eventId/dashboard'
    | '/events/$eventId/details'
    | '/events/$eventId/edit'
    | '/events/$eventId/food'
    | '/events/$eventId/links'
    | '/events/$eventId/media'
    | '/events/$eventId/notifications'
    | '/events/$eventId/payments'
    | '/events/$eventId/preview'
    | '/events/$eventId/quick-entry'
    | '/events/$eventId/registrations'
    | '/events/$eventId/seating'
    | '/events/$eventId/sponsors'
    | '/npos/$npoId/edit'
    | '/npos/$npoId/payment-settings'
    | '/events/$eventId'
    | '/npos/$npoId'
    | '/users/$userId'
    | '/events/$eventId/auction-items/create'
    | '/events/$eventId/tickets/create'
    | '/events/$eventId/tickets/promos'
    | '/events/$eventId/tickets/sales'
    | '/events/$eventId/auction-items'
    | '/events/$eventId/tickets'
    | '/events/$eventId/auction-items/$itemId/edit'
    | '/events/$eventId/auction-items/$itemId/engagement'
    | '/events/$eventId/tickets/$packageId/edit'
    | '/events/$eventId/auction-items/$itemId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/donor-portal-redirect'
    | '/_authenticated/events'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/complete-profile'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/password-reset'
    | '/(auth)/password-reset-confirm'
    | '/(auth)/privacy-policy'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(auth)/social-callback'
    | '/(auth)/terms-of-service'
    | '/(auth)/verify-email'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/invitations/accept'
    | '/_authenticated/'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/admin/npo-applications'
    | '/_authenticated/errors/$error'
    | '/_authenticated/events/create'
    | '/_authenticated/npos/create'
    | '/_authenticated/settings/consent'
    | '/_authenticated/settings/password'
    | '/_authenticated/settings/support'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/(auth)/register-npo/'
    | '/_authenticated/events/'
    | '/_authenticated/npos/'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/_authenticated/events/$eventId/auction-bids'
    | '/_authenticated/events/$eventId/auction-items'
    | '/_authenticated/events/$eventId/checkin'
    | '/_authenticated/events/$eventId/checklist'
    | '/_authenticated/events/$eventId/dashboard'
    | '/_authenticated/events/$eventId/details'
    | '/_authenticated/events/$eventId/edit'
    | '/_authenticated/events/$eventId/food'
    | '/_authenticated/events/$eventId/links'
    | '/_authenticated/events/$eventId/media'
    | '/_authenticated/events/$eventId/notifications'
    | '/_authenticated/events/$eventId/payments'
    | '/_authenticated/events/$eventId/preview'
    | '/_authenticated/events/$eventId/quick-entry'
    | '/_authenticated/events/$eventId/registrations'
    | '/_authenticated/events/$eventId/seating'
    | '/_authenticated/events/$eventId/sponsors'
    | '/_authenticated/events/$eventId/tickets'
    | '/_authenticated/npos/$npoId/edit'
    | '/_authenticated/npos/$npoId/payment-settings'
    | '/_authenticated/events/$eventId/'
    | '/_authenticated/npos/$npoId/'
    | '/_authenticated/users/$userId/'
    | '/_authenticated/events/$eventId/auction-items/create'
    | '/_authenticated/events/$eventId/tickets/create'
    | '/_authenticated/events/$eventId/tickets/promos'
    | '/_authenticated/events/$eventId/tickets/sales'
    | '/_authenticated/events/$eventId/auction-items/'
    | '/_authenticated/events/$eventId/tickets/'
    | '/_authenticated/events/$eventId/auction-items/$itemId/edit'
    | '/_authenticated/events/$eventId/auction-items/$itemId/engagement'
    | '/_authenticated/events/$eventId/tickets/$packageId/edit'
    | '/_authenticated/events/$eventId/auction-items/$itemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  DonorPortalRedirectRoute: typeof DonorPortalRedirectRoute
  authCompleteProfileRoute: typeof authCompleteProfileRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authPasswordResetRoute: typeof authPasswordResetRoute
  authPasswordResetConfirmRoute: typeof authPasswordResetConfirmRoute
  authPrivacyPolicyRoute: typeof authPrivacyPolicyRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  authSocialCallbackRoute: typeof authSocialCallbackRoute
  authTermsOfServiceRoute: typeof authTermsOfServiceRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  authRegisterNpoIndexRoute: typeof authRegisterNpoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/donor-portal-redirect': {
      id: '/donor-portal-redirect'
      path: '/donor-portal-redirect'
      fullPath: '/donor-portal-redirect'
      preLoaderRoute: typeof DonorPortalRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/terms-of-service': {
      id: '/(auth)/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof authTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/social-callback': {
      id: '/(auth)/social-callback'
      path: '/social-callback'
      fullPath: '/social-callback'
      preLoaderRoute: typeof authSocialCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/privacy-policy': {
      id: '/(auth)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof authPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/password-reset-confirm': {
      id: '/(auth)/password-reset-confirm'
      path: '/password-reset-confirm'
      fullPath: '/password-reset-confirm'
      preLoaderRoute: typeof authPasswordResetConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/password-reset': {
      id: '/(auth)/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof authPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/complete-profile': {
      id: '/(auth)/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof authCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/npos/': {
      id: '/_authenticated/npos/'
      path: '/npos'
      fullPath: '/npos/'
      preLoaderRoute: typeof AuthenticatedNposIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedEventsRouteRoute
    }
    '/(auth)/register-npo/': {
      id: '/(auth)/register-npo/'
      path: '/register-npo'
      fullPath: '/register-npo/'
      preLoaderRoute: typeof authRegisterNpoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/support': {
      id: '/_authenticated/settings/support'
      path: '/support'
      fullPath: '/settings/support'
      preLoaderRoute: typeof AuthenticatedSettingsSupportRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/password': {
      id: '/_authenticated/settings/password'
      path: '/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof AuthenticatedSettingsPasswordRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/consent': {
      id: '/_authenticated/settings/consent'
      path: '/consent'
      fullPath: '/settings/consent'
      preLoaderRoute: typeof AuthenticatedSettingsConsentRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/npos/create': {
      id: '/_authenticated/npos/create'
      path: '/npos/create'
      fullPath: '/npos/create'
      preLoaderRoute: typeof AuthenticatedNposCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/create': {
      id: '/_authenticated/events/create'
      path: '/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof AuthenticatedEventsCreateRouteImport
      parentRoute: typeof AuthenticatedEventsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/npo-applications': {
      id: '/_authenticated/admin/npo-applications'
      path: '/admin/npo-applications'
      fullPath: '/admin/npo-applications'
      preLoaderRoute: typeof AuthenticatedAdminNpoApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteRouteImport
      parentRoute: typeof AuthenticatedEventsRouteRoute
    }
    '/_authenticated/users/$userId/': {
      id: '/_authenticated/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof AuthenticatedUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/npos/$npoId/': {
      id: '/_authenticated/npos/$npoId/'
      path: '/npos/$npoId'
      fullPath: '/npos/$npoId/'
      preLoaderRoute: typeof AuthenticatedNposNpoIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventId/': {
      id: '/_authenticated/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AuthenticatedEventsEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/npos/$npoId/payment-settings': {
      id: '/_authenticated/npos/$npoId/payment-settings'
      path: '/npos/$npoId/payment-settings'
      fullPath: '/npos/$npoId/payment-settings'
      preLoaderRoute: typeof AuthenticatedNposNpoIdPaymentSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/npos/$npoId/edit': {
      id: '/_authenticated/npos/$npoId/edit'
      path: '/npos/$npoId/edit'
      fullPath: '/npos/$npoId/edit'
      preLoaderRoute: typeof AuthenticatedNposNpoIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventId/tickets': {
      id: '/_authenticated/events/$eventId/tickets'
      path: '/tickets'
      fullPath: '/events/$eventId/tickets'
      preLoaderRoute: typeof AuthenticatedEventsEventIdTicketsRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/sponsors': {
      id: '/_authenticated/events/$eventId/sponsors'
      path: '/sponsors'
      fullPath: '/events/$eventId/sponsors'
      preLoaderRoute: typeof AuthenticatedEventsEventIdSponsorsRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/seating': {
      id: '/_authenticated/events/$eventId/seating'
      path: '/seating'
      fullPath: '/events/$eventId/seating'
      preLoaderRoute: typeof AuthenticatedEventsEventIdSeatingRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/registrations': {
      id: '/_authenticated/events/$eventId/registrations'
      path: '/registrations'
      fullPath: '/events/$eventId/registrations'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRegistrationsRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/quick-entry': {
      id: '/_authenticated/events/$eventId/quick-entry'
      path: '/quick-entry'
      fullPath: '/events/$eventId/quick-entry'
      preLoaderRoute: typeof AuthenticatedEventsEventIdQuickEntryRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/preview': {
      id: '/_authenticated/events/$eventId/preview'
      path: '/preview'
      fullPath: '/events/$eventId/preview'
      preLoaderRoute: typeof AuthenticatedEventsEventIdPreviewRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/payments': {
      id: '/_authenticated/events/$eventId/payments'
      path: '/payments'
      fullPath: '/events/$eventId/payments'
      preLoaderRoute: typeof AuthenticatedEventsEventIdPaymentsRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/notifications': {
      id: '/_authenticated/events/$eventId/notifications'
      path: '/notifications'
      fullPath: '/events/$eventId/notifications'
      preLoaderRoute: typeof AuthenticatedEventsEventIdNotificationsRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/media': {
      id: '/_authenticated/events/$eventId/media'
      path: '/media'
      fullPath: '/events/$eventId/media'
      preLoaderRoute: typeof AuthenticatedEventsEventIdMediaRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/links': {
      id: '/_authenticated/events/$eventId/links'
      path: '/links'
      fullPath: '/events/$eventId/links'
      preLoaderRoute: typeof AuthenticatedEventsEventIdLinksRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/food': {
      id: '/_authenticated/events/$eventId/food'
      path: '/food'
      fullPath: '/events/$eventId/food'
      preLoaderRoute: typeof AuthenticatedEventsEventIdFoodRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/edit': {
      id: '/_authenticated/events/$eventId/edit'
      path: '/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof AuthenticatedEventsEventIdEditRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/details': {
      id: '/_authenticated/events/$eventId/details'
      path: '/details'
      fullPath: '/events/$eventId/details'
      preLoaderRoute: typeof AuthenticatedEventsEventIdDetailsRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/dashboard': {
      id: '/_authenticated/events/$eventId/dashboard'
      path: '/dashboard'
      fullPath: '/events/$eventId/dashboard'
      preLoaderRoute: typeof AuthenticatedEventsEventIdDashboardRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/checklist': {
      id: '/_authenticated/events/$eventId/checklist'
      path: '/checklist'
      fullPath: '/events/$eventId/checklist'
      preLoaderRoute: typeof AuthenticatedEventsEventIdChecklistRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/checkin': {
      id: '/_authenticated/events/$eventId/checkin'
      path: '/checkin'
      fullPath: '/events/$eventId/checkin'
      preLoaderRoute: typeof AuthenticatedEventsEventIdCheckinRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/auction-items': {
      id: '/_authenticated/events/$eventId/auction-items'
      path: '/auction-items'
      fullPath: '/events/$eventId/auction-items'
      preLoaderRoute: typeof AuthenticatedEventsEventIdAuctionItemsRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/auction-bids': {
      id: '/_authenticated/events/$eventId/auction-bids'
      path: '/auction-bids'
      fullPath: '/events/$eventId/auction-bids'
      preLoaderRoute: typeof AuthenticatedEventsEventIdAuctionBidsRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRouteRoute
    }
    '/_authenticated/events/$eventId/tickets/': {
      id: '/_authenticated/events/$eventId/tickets/'
      path: '/'
      fullPath: '/events/$eventId/tickets/'
      preLoaderRoute: typeof AuthenticatedEventsEventIdTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdTicketsRoute
    }
    '/_authenticated/events/$eventId/auction-items/': {
      id: '/_authenticated/events/$eventId/auction-items/'
      path: '/'
      fullPath: '/events/$eventId/auction-items/'
      preLoaderRoute: typeof AuthenticatedEventsEventIdAuctionItemsIndexRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdAuctionItemsRoute
    }
    '/_authenticated/events/$eventId/tickets/sales': {
      id: '/_authenticated/events/$eventId/tickets/sales'
      path: '/sales'
      fullPath: '/events/$eventId/tickets/sales'
      preLoaderRoute: typeof AuthenticatedEventsEventIdTicketsSalesRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdTicketsRoute
    }
    '/_authenticated/events/$eventId/tickets/promos': {
      id: '/_authenticated/events/$eventId/tickets/promos'
      path: '/promos'
      fullPath: '/events/$eventId/tickets/promos'
      preLoaderRoute: typeof AuthenticatedEventsEventIdTicketsPromosRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdTicketsRoute
    }
    '/_authenticated/events/$eventId/tickets/create': {
      id: '/_authenticated/events/$eventId/tickets/create'
      path: '/create'
      fullPath: '/events/$eventId/tickets/create'
      preLoaderRoute: typeof AuthenticatedEventsEventIdTicketsCreateRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdTicketsRoute
    }
    '/_authenticated/events/$eventId/auction-items/create': {
      id: '/_authenticated/events/$eventId/auction-items/create'
      path: '/create'
      fullPath: '/events/$eventId/auction-items/create'
      preLoaderRoute: typeof AuthenticatedEventsEventIdAuctionItemsCreateRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdAuctionItemsRoute
    }
    '/_authenticated/events/$eventId/auction-items/$itemId/': {
      id: '/_authenticated/events/$eventId/auction-items/$itemId/'
      path: '/$itemId'
      fullPath: '/events/$eventId/auction-items/$itemId/'
      preLoaderRoute: typeof AuthenticatedEventsEventIdAuctionItemsItemIdIndexRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdAuctionItemsRoute
    }
    '/_authenticated/events/$eventId/tickets/$packageId/edit': {
      id: '/_authenticated/events/$eventId/tickets/$packageId/edit'
      path: '/$packageId/edit'
      fullPath: '/events/$eventId/tickets/$packageId/edit'
      preLoaderRoute: typeof AuthenticatedEventsEventIdTicketsPackageIdEditRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdTicketsRoute
    }
    '/_authenticated/events/$eventId/auction-items/$itemId/engagement': {
      id: '/_authenticated/events/$eventId/auction-items/$itemId/engagement'
      path: '/$itemId/engagement'
      fullPath: '/events/$eventId/auction-items/$itemId/engagement'
      preLoaderRoute: typeof AuthenticatedEventsEventIdAuctionItemsItemIdEngagementRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdAuctionItemsRoute
    }
    '/_authenticated/events/$eventId/auction-items/$itemId/edit': {
      id: '/_authenticated/events/$eventId/auction-items/$itemId/edit'
      path: '/$itemId/edit'
      fullPath: '/events/$eventId/auction-items/$itemId/edit'
      preLoaderRoute: typeof AuthenticatedEventsEventIdAuctionItemsItemIdEditRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdAuctionItemsRoute
    }
  }
}

interface AuthenticatedEventsEventIdAuctionItemsRouteChildren {
  AuthenticatedEventsEventIdAuctionItemsCreateRoute: typeof AuthenticatedEventsEventIdAuctionItemsCreateRoute
  AuthenticatedEventsEventIdAuctionItemsIndexRoute: typeof AuthenticatedEventsEventIdAuctionItemsIndexRoute
  AuthenticatedEventsEventIdAuctionItemsItemIdEditRoute: typeof AuthenticatedEventsEventIdAuctionItemsItemIdEditRoute
  AuthenticatedEventsEventIdAuctionItemsItemIdEngagementRoute: typeof AuthenticatedEventsEventIdAuctionItemsItemIdEngagementRoute
  AuthenticatedEventsEventIdAuctionItemsItemIdIndexRoute: typeof AuthenticatedEventsEventIdAuctionItemsItemIdIndexRoute
}

const AuthenticatedEventsEventIdAuctionItemsRouteChildren: AuthenticatedEventsEventIdAuctionItemsRouteChildren =
  {
    AuthenticatedEventsEventIdAuctionItemsCreateRoute:
      AuthenticatedEventsEventIdAuctionItemsCreateRoute,
    AuthenticatedEventsEventIdAuctionItemsIndexRoute:
      AuthenticatedEventsEventIdAuctionItemsIndexRoute,
    AuthenticatedEventsEventIdAuctionItemsItemIdEditRoute:
      AuthenticatedEventsEventIdAuctionItemsItemIdEditRoute,
    AuthenticatedEventsEventIdAuctionItemsItemIdEngagementRoute:
      AuthenticatedEventsEventIdAuctionItemsItemIdEngagementRoute,
    AuthenticatedEventsEventIdAuctionItemsItemIdIndexRoute:
      AuthenticatedEventsEventIdAuctionItemsItemIdIndexRoute,
  }

const AuthenticatedEventsEventIdAuctionItemsRouteWithChildren =
  AuthenticatedEventsEventIdAuctionItemsRoute._addFileChildren(
    AuthenticatedEventsEventIdAuctionItemsRouteChildren,
  )

interface AuthenticatedEventsEventIdTicketsRouteChildren {
  AuthenticatedEventsEventIdTicketsCreateRoute: typeof AuthenticatedEventsEventIdTicketsCreateRoute
  AuthenticatedEventsEventIdTicketsPromosRoute: typeof AuthenticatedEventsEventIdTicketsPromosRoute
  AuthenticatedEventsEventIdTicketsSalesRoute: typeof AuthenticatedEventsEventIdTicketsSalesRoute
  AuthenticatedEventsEventIdTicketsIndexRoute: typeof AuthenticatedEventsEventIdTicketsIndexRoute
  AuthenticatedEventsEventIdTicketsPackageIdEditRoute: typeof AuthenticatedEventsEventIdTicketsPackageIdEditRoute
}

const AuthenticatedEventsEventIdTicketsRouteChildren: AuthenticatedEventsEventIdTicketsRouteChildren =
  {
    AuthenticatedEventsEventIdTicketsCreateRoute:
      AuthenticatedEventsEventIdTicketsCreateRoute,
    AuthenticatedEventsEventIdTicketsPromosRoute:
      AuthenticatedEventsEventIdTicketsPromosRoute,
    AuthenticatedEventsEventIdTicketsSalesRoute:
      AuthenticatedEventsEventIdTicketsSalesRoute,
    AuthenticatedEventsEventIdTicketsIndexRoute:
      AuthenticatedEventsEventIdTicketsIndexRoute,
    AuthenticatedEventsEventIdTicketsPackageIdEditRoute:
      AuthenticatedEventsEventIdTicketsPackageIdEditRoute,
  }

const AuthenticatedEventsEventIdTicketsRouteWithChildren =
  AuthenticatedEventsEventIdTicketsRoute._addFileChildren(
    AuthenticatedEventsEventIdTicketsRouteChildren,
  )

interface AuthenticatedEventsEventIdRouteRouteChildren {
  AuthenticatedEventsEventIdAuctionBidsRoute: typeof AuthenticatedEventsEventIdAuctionBidsRoute
  AuthenticatedEventsEventIdAuctionItemsRoute: typeof AuthenticatedEventsEventIdAuctionItemsRouteWithChildren
  AuthenticatedEventsEventIdCheckinRoute: typeof AuthenticatedEventsEventIdCheckinRoute
  AuthenticatedEventsEventIdChecklistRoute: typeof AuthenticatedEventsEventIdChecklistRoute
  AuthenticatedEventsEventIdDashboardRoute: typeof AuthenticatedEventsEventIdDashboardRoute
  AuthenticatedEventsEventIdDetailsRoute: typeof AuthenticatedEventsEventIdDetailsRoute
  AuthenticatedEventsEventIdEditRoute: typeof AuthenticatedEventsEventIdEditRoute
  AuthenticatedEventsEventIdFoodRoute: typeof AuthenticatedEventsEventIdFoodRoute
  AuthenticatedEventsEventIdLinksRoute: typeof AuthenticatedEventsEventIdLinksRoute
  AuthenticatedEventsEventIdMediaRoute: typeof AuthenticatedEventsEventIdMediaRoute
  AuthenticatedEventsEventIdNotificationsRoute: typeof AuthenticatedEventsEventIdNotificationsRoute
  AuthenticatedEventsEventIdPaymentsRoute: typeof AuthenticatedEventsEventIdPaymentsRoute
  AuthenticatedEventsEventIdPreviewRoute: typeof AuthenticatedEventsEventIdPreviewRoute
  AuthenticatedEventsEventIdQuickEntryRoute: typeof AuthenticatedEventsEventIdQuickEntryRoute
  AuthenticatedEventsEventIdRegistrationsRoute: typeof AuthenticatedEventsEventIdRegistrationsRoute
  AuthenticatedEventsEventIdSeatingRoute: typeof AuthenticatedEventsEventIdSeatingRoute
  AuthenticatedEventsEventIdSponsorsRoute: typeof AuthenticatedEventsEventIdSponsorsRoute
  AuthenticatedEventsEventIdTicketsRoute: typeof AuthenticatedEventsEventIdTicketsRouteWithChildren
  AuthenticatedEventsEventIdIndexRoute: typeof AuthenticatedEventsEventIdIndexRoute
}

const AuthenticatedEventsEventIdRouteRouteChildren: AuthenticatedEventsEventIdRouteRouteChildren =
  {
    AuthenticatedEventsEventIdAuctionBidsRoute:
      AuthenticatedEventsEventIdAuctionBidsRoute,
    AuthenticatedEventsEventIdAuctionItemsRoute:
      AuthenticatedEventsEventIdAuctionItemsRouteWithChildren,
    AuthenticatedEventsEventIdCheckinRoute:
      AuthenticatedEventsEventIdCheckinRoute,
    AuthenticatedEventsEventIdChecklistRoute:
      AuthenticatedEventsEventIdChecklistRoute,
    AuthenticatedEventsEventIdDashboardRoute:
      AuthenticatedEventsEventIdDashboardRoute,
    AuthenticatedEventsEventIdDetailsRoute:
      AuthenticatedEventsEventIdDetailsRoute,
    AuthenticatedEventsEventIdEditRoute: AuthenticatedEventsEventIdEditRoute,
    AuthenticatedEventsEventIdFoodRoute: AuthenticatedEventsEventIdFoodRoute,
    AuthenticatedEventsEventIdLinksRoute: AuthenticatedEventsEventIdLinksRoute,
    AuthenticatedEventsEventIdMediaRoute: AuthenticatedEventsEventIdMediaRoute,
    AuthenticatedEventsEventIdNotificationsRoute:
      AuthenticatedEventsEventIdNotificationsRoute,
    AuthenticatedEventsEventIdPaymentsRoute:
      AuthenticatedEventsEventIdPaymentsRoute,
    AuthenticatedEventsEventIdPreviewRoute:
      AuthenticatedEventsEventIdPreviewRoute,
    AuthenticatedEventsEventIdQuickEntryRoute:
      AuthenticatedEventsEventIdQuickEntryRoute,
    AuthenticatedEventsEventIdRegistrationsRoute:
      AuthenticatedEventsEventIdRegistrationsRoute,
    AuthenticatedEventsEventIdSeatingRoute:
      AuthenticatedEventsEventIdSeatingRoute,
    AuthenticatedEventsEventIdSponsorsRoute:
      AuthenticatedEventsEventIdSponsorsRoute,
    AuthenticatedEventsEventIdTicketsRoute:
      AuthenticatedEventsEventIdTicketsRouteWithChildren,
    AuthenticatedEventsEventIdIndexRoute: AuthenticatedEventsEventIdIndexRoute,
  }

const AuthenticatedEventsEventIdRouteRouteWithChildren =
  AuthenticatedEventsEventIdRouteRoute._addFileChildren(
    AuthenticatedEventsEventIdRouteRouteChildren,
  )

interface AuthenticatedEventsRouteRouteChildren {
  AuthenticatedEventsEventIdRouteRoute: typeof AuthenticatedEventsEventIdRouteRouteWithChildren
  AuthenticatedEventsCreateRoute: typeof AuthenticatedEventsCreateRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
}

const AuthenticatedEventsRouteRouteChildren: AuthenticatedEventsRouteRouteChildren =
  {
    AuthenticatedEventsEventIdRouteRoute:
      AuthenticatedEventsEventIdRouteRouteWithChildren,
    AuthenticatedEventsCreateRoute: AuthenticatedEventsCreateRoute,
    AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  }

const AuthenticatedEventsRouteRouteWithChildren =
  AuthenticatedEventsRouteRoute._addFileChildren(
    AuthenticatedEventsRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsConsentRoute: typeof AuthenticatedSettingsConsentRoute
  AuthenticatedSettingsPasswordRoute: typeof AuthenticatedSettingsPasswordRoute
  AuthenticatedSettingsSupportRoute: typeof AuthenticatedSettingsSupportRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsConsentRoute: AuthenticatedSettingsConsentRoute,
    AuthenticatedSettingsPasswordRoute: AuthenticatedSettingsPasswordRoute,
    AuthenticatedSettingsSupportRoute: AuthenticatedSettingsSupportRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEventsRouteRoute: typeof AuthenticatedEventsRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminNpoApplicationsRoute: typeof AuthenticatedAdminNpoApplicationsRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedNposCreateRoute: typeof AuthenticatedNposCreateRoute
  AuthenticatedNposIndexRoute: typeof AuthenticatedNposIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedNposNpoIdEditRoute: typeof AuthenticatedNposNpoIdEditRoute
  AuthenticatedNposNpoIdPaymentSettingsRoute: typeof AuthenticatedNposNpoIdPaymentSettingsRoute
  AuthenticatedNposNpoIdIndexRoute: typeof AuthenticatedNposNpoIdIndexRoute
  AuthenticatedUsersUserIdIndexRoute: typeof AuthenticatedUsersUserIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEventsRouteRoute: AuthenticatedEventsRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminNpoApplicationsRoute:
    AuthenticatedAdminNpoApplicationsRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedNposCreateRoute: AuthenticatedNposCreateRoute,
  AuthenticatedNposIndexRoute: AuthenticatedNposIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedNposNpoIdEditRoute: AuthenticatedNposNpoIdEditRoute,
  AuthenticatedNposNpoIdPaymentSettingsRoute:
    AuthenticatedNposNpoIdPaymentSettingsRoute,
  AuthenticatedNposNpoIdIndexRoute: AuthenticatedNposNpoIdIndexRoute,
  AuthenticatedUsersUserIdIndexRoute: AuthenticatedUsersUserIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  DonorPortalRedirectRoute: DonorPortalRedirectRoute,
  authCompleteProfileRoute: authCompleteProfileRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authPasswordResetRoute: authPasswordResetRoute,
  authPasswordResetConfirmRoute: authPasswordResetConfirmRoute,
  authPrivacyPolicyRoute: authPrivacyPolicyRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  authSocialCallbackRoute: authSocialCallbackRoute,
  authTermsOfServiceRoute: authTermsOfServiceRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  authRegisterNpoIndexRoute: authRegisterNpoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
