#!/bin/bash
# Test script for URL validation in branding page

echo "=========================================="
echo "NPO Branding URL Validation Test"
echo "=========================================="
echo ""

echo "✅ Validation functions added:"
echo "   - isValidUrl(): Validates http:// and https:// URLs"
echo "   - validateSocialUrl(): Checks URLs on change/blur"
echo "   - URL validation in handleSave()"
echo ""

echo "✅ Visual feedback implemented:"
echo "   - Red border on invalid URLs"
echo "   - AlertCircle icon with error message"
echo "   - Validation on change and blur events"
echo ""

echo "✅ User Experience:"
echo "   - Real-time validation as user types"
echo "   - Validation on blur (when leaving field)"
echo "   - Blocks save if any URL is invalid"
echo "   - Toast error message on save attempt with invalid URLs"
echo ""

echo "📋 Test Cases:"
echo ""
echo "Valid URLs (should pass):"
echo "   ✓ https://facebook.com/mypage"
echo "   ✓ http://twitter.com/handle"
echo "   ✓ https://instagram.com/user"
echo "   ✓ Empty string (optional field)"
echo ""

echo "Invalid URLs (should show error):"
echo "   ✗ facebook.com/mypage (missing protocol)"
echo "   ✗ www.facebook.com/mypage (missing protocol)"
echo "   ✗ ftp://facebook.com (wrong protocol)"
echo "   ✗ just some text (not a URL)"
echo ""

echo "🌐 To test manually:"
echo "   1. Open http://localhost:5173/npos"
echo "   2. Click on an NPO"
echo "   3. Click 'Branding' button"
echo "   4. Scroll to 'Social Media Links' section"
echo "   5. Try entering invalid URLs (without https://)"
echo "   6. See red border and error message appear"
echo "   7. Try to save - should see error toast"
echo "   8. Fix URLs to valid format"
echo "   9. Save should succeed"
echo ""

echo "=========================================="
echo "Additional Features Available (unused):"
echo "=========================================="
echo ""
echo "• isValidEmail(): Email validation (ready for future use)"
echo "• formatPhoneNumber(): US phone formatting (ready for future use)"
echo ""
echo "Note: These can be used if NPO creation/edit forms need"
echo "      email or phone validation in the future."
echo ""
